var digi = {
	"aeroveedramon": {"name": "AeroVeedramon", "evol": "ultimate", "next": ["ravemon", "dynasmon", "ulforceveedramon"], "tribe": "mirage", "skills": [["earth", 1]], "v2": 0},
	"agumon": {"name": "Agumon", "evol": "rookie", "next": ["geogreymon", "greymon", "meramon", "tyrannomon", "sukamon"], "tribe": "blazing", "skills": [["blazing", 1]], "v2": 0},
	"agumon-black": {"name": "Agumon (Black)", "evol": "rookie", "next": ["growlmon", "cyclonemon", "tankmon", "tyrannomon", "greymon-blue"], "tribe": "blazing", "skills": [["blazing", 1]], "v2": 0},
	"alphamon": {"name": "Alphamon", "evol": "mega", "next": [], "tribe": "bright", "skills": [["bright", 1, "SSS"], ["mirage", 2, "B"]], "v2": 0},
	"ancientgarurumon": {"name": "AncientGarurumon", "evol": "mega", "next": [], "tribe": "bright", "skills": [["bright", 1, "S"]], "v2": 0},
	"ancientgreymon": {"name": "AncientGreymon", "evol": "mega", "next": [], "tribe": "blazing", "skills": [["blazing", 1, "A"]], "v2": 0},
	"andromon": {"name": "Andromon", "evol": "ultimate", "next": ["craniamon", "hiandromon", "tigervespamon"], "tribe": "electric", "skills": [["electric", 1]], "v2": 0},
	"angemon": {"name": "Angemon", "evol": "champion", "next": ["garudamon", "magnaangemon", "shakkoumon", "kimeramon"], "tribe": "bright", "skills": [["bright", 1]], "v2": 0},
	"angewomon": {"name": "Angewomon", "evol": "ultimate", "next": ["magnadramon", "ophanimon", "mastemon", "ophanimon-fm"], "tribe": "bright", "skills": [["bright", 1]], "v2": 0},
	"ankylomon": {"name": "Ankylomon", "evol": "champion", "next": ["magnaangemon", "meteormon", "shakkoumon", "skullgreymon"], "tribe": "earth", "skills": [["earth", 1]], "v2": 0},
	"antylamon": {"name": "Antylamon", "evol": "ultimate", "next": ["cherubimon-good", "dianamon", "diaboromon", "chaosgallantmon"], "tribe": "mirage", "skills": [["earth", 1]], "v2": 0},
	"aquilamon": {"name": "Aquilamon", "evol": "champion", "next": ["aeroveedramon", "garudamon", "silphymon", "crowmon"], "tribe": "mirage", "skills": [["earth", 1]], "v2": 0},
	"armadillomon": {"name": "Armadillomon", "evol": "rookie", "next": ["ankylomon", "cyclonemon", "goldnumemon", "tankmon", "geremon"], "tribe": "earth", "skills": [["earth", 1]], "v2": 0},
	"armageddemon": {"name": "Armageddemon", "evol": "mega", "next": [], "tribe": "abyss", "skills": [["blazing", 1]], "v2": 0},
	"arresterdramon": {"name": "Arresterdramon", "evol": "mega", "next": [], "tribe": "blazing", "skills": [["abyss", 2]], "v2": 0},
	"bakemon": {"name": "Bakemon", "evol": "champion", "next": ["bluemeramon", "pumpkinmon", "myotismon", "ladydevimon"], "tribe": "abyss", "skills": [["mirage", 1]], "v2": 0},
	"bancholeomon": {"name": "BanchoLeomon", "evol": "mega", "next": [], "tribe": "earth", "skills": [["bright", 1, "S"]], "v2": 0},
	"barbamon": {"name": "Barbamon", "evol": "mega", "next": [], "tribe": "abyss", "skills": [["abyss", 2, "A"]], "v2": 0},
	"beelzemon": {"name": "Beelzemon", "evol": "mega", "next": ["beelzemon-x"], "tribe": "abyss", "skills": [["abyss", 1, "SSS"]], "v2": 0},
	"beelzemon-x": {"name": "Beelzemon X", "evol": "mega", "next": [], "tribe": "abyss", "skills": [["abyss", 1]], "v2": 0},
	"belphemon-rm": {"name": "Belphemon RM", "evol": "mega", "next": ["belphemon-sm"], "tribe": "abyss", "skills": [["abyss", 1, "GOD"]], "v2": 0},
	"belphemon-sm": {"name": "Belphemon SM", "evol": "mega", "next": ["belphemon-rm"], "tribe": "abyss", "skills": [["abyss", 2, "B"]], "v2": 0},
	"betamon": {"name": "Betamon", "evol": "rookie", "next": ["gekomon", "numemon", "seadramon", "shellnumemon", "vegiemon"], "tribe": "glacier", "skills": [["electric", 1]], "v2": 0},
	"birdramon": {"name": "Birdramon", "evol": "champion", "next": ["aeroveedramon", "garudamon", "chirinmon", "crowmon"], "tribe": "blazing", "skills": [["blazing", 2]], "v2": 0},
	"biyomon": {"name": "Biyomon", "evol": "rookie", "next": ["kabuterimon", "aquilamon", "birdramon", "kyubimon"], "tribe": "mirage", "skills": [["blazing", 1]], "v2": 0},
	"blackgatomon": {"name": "BlackGatomon", "evol": "champion", "next": ["cyberdramon", "knightmon", "ladydevimon", "weregarurumon-black"], "tribe": "abyss", "skills": [["mirage", 1]], "v2": 0},
	"blackkingnumemon": {"name": "BlackKingNumemon", "evol": "ultimate", "next": ["platinumnumemon", "metaletemon", "princemamemon"], "tribe": "abyss", "skills": [["abyss", 1]], "v2": 0},
	"blackwargreymon": {"name": "BlackWarGreymon", "evol": "mega", "next": ["omegamon-zwart", "blackwargreymon-x"], "tribe": "blazing", "skills": [["abyss", 2, "C"], ["abyss", 1, "B"]], "v2": 0},
	"blackwargreymon-x": {"name": "BlackWarGreymon X", "evol": "mega", "next": [], "tribe": "blazing", "skills": [["abyss", 1, "SS"]], "v2": 0},
	"blitzgreymon": {"name": "BlitzGreymon", "evol": "mega", "next": ["omegamon-alter-s"], "tribe": "electric", "skills": [["electric", 1, "A"]], "v2": 0},
	"bluemeramon": {"name": "BlueMeramon", "evol": "ultimate", "next": ["barbamon", "boltmon", "creepymon"], "tribe": "blazing", "skills": [["blazing", 1]], "v2": 0},
	"boltmon": {"name": "Boltmon", "evol": "mega", "next": [], "tribe": "electric", "skills": [["mirage", 1, "A"]], "v2": 1},
	"botamon": {"name": "Botamon", "evol": "in-training-i", "next": ["koromon", "wanyamon"], "tribe": "mirage", "skills": [["mirage", 1]], "v2": 0},
	"brakedramon": {"name": "Brakedramon", "evol": "mega", "next": ["examon"], "tribe": "electric", "skills": [["earth", 1, "SS"]], "v2": 0},
	"bukamon": {"name": "Bukamon", "evol": "in-training-ii", "next": ["otamamon", "gomamon", "syakomon", "betamon"], "tribe": "mirage", "skills": [["mirage", 1]], "v2": 0},
	"cannonbeemon": {"name": "CannonBeemon", "evol": "ultimate", "next": ["megagargomon", "groundlocomon", "tigervespamon"], "tribe": "electric", "skills": [["electric", 1]], "v2": 0},
	"chaosdramon": {"name": "Chaosdramon", "evol": "mega", "next": [], "tribe": "electric", "skills": [["electric", 2, "SS"]], "v2": 0},
	"chaosgallantmon": {"name": "ChaosGallantmon", "evol": "mega", "next": [], "tribe": "abyss", "skills": [["abyss", 1, "B"], ["abyss", 2, "B"]], "v2": 1},
	"cherrymon": {"name": "Cherrymon", "evol": "ultimate", "next": ["grankuwagamon", "kuzuhamon", "puppetmon"], "tribe": "earth", "skills": [["earth", 2]], "v2": 0},
	"cherubimon-good": {"name": "Cherubimon (Good)", "evol": "mega", "next": [], "tribe": "bright", "skills": [["bright", 1, "SSS*"]], "v2": 1},
	"chirinmon": {"name": "Chirinmon", "evol": "ultimate", "next": ["ophanimon", "seraphimon", "kentaurosmon"], "tribe": "bright", "skills": [["earth", 1]], "v2": 0},
	"chrysalimon": {"name": "Chrysalimon", "evol": "champion", "next": ["cyberdramon", "infermon", "taomon"], "tribe": "abyss", "skills": [["abyss", 1]], "v2": 0},
	"clockmon": {"name": "Clockmon", "evol": "champion", "next": ["andromon", "knightmon", "datamon", "wisemon"], "tribe": "electric", "skills": [["mirage", 1]], "v2": 0},
	"coredramon-blue": {"name": "Coredramon (Blue)", "evol": "champion", "next": ["wingdramon"], "tribe": "blazing", "skills": [["blazing", 1]], "v2": 0},
	"coredramon-green": {"name": "Coredramon (Green)", "evol": "champion", "next": ["groundramon"], "tribe": "earth", "skills": [["earth", 1]], "v2": 0},
	"craniamon": {"name": "Craniamon", "evol": "mega", "next": [], "tribe": "earth", "skills": [["earth", 2, "SS"], ["mirage", 0, "F"]], "v2": 0},
	"creepymon": {"name": "Creepymon", "evol": "mega", "next": [], "tribe": "abyss", "skills": [["blazing", 2, "A"]], "v2": 0},
	"cresgarurumon": {"name": "CresGarurumon", "evol": "mega", "next": ["omegamon-alter-s"], "tribe": "earth", "skills": [["earth", 1, "SS"]], "v2": 0},
	"crowmon": {"name": "Crowmon", "evol": "ultimate", "next": ["minervamon", "ravemon", "kuzuhamon"], "tribe": "mirage", "skills": [["bright", 1]], "v2": 0},
	"cyberdramon": {"name": "Cyberdramon", "evol": "ultimate", "next": ["justimon", "titamon", "alphamon"], "tribe": "abyss", "skills": [["mirage", 1]], "v2": 0},
	"cyclonemon": {"name": "Cyclonemon", "evol": "champion", "next": ["megadramon", "dorugreymon", "datamon"], "tribe": "earth", "skills": [["blazing", 2]], "v2": 0},
	"datamon": {"name": "Datamon", "evol": "ultimate", "next": ["machinedramon", "metalgarurumon-black", "groundlocomon"], "tribe": "electric", "skills": [["blazing", 1]], "v2": 0},
	"demidevimon": {"name": "DemiDevimon", "evol": "rookie", "next": ["bakemon", "devimon", "kyubimon", "chrysalimon", "icedevimon"], "tribe": "abyss", "skills": [["abyss", 1]], "v2": 0},
	"devimon": {"name": "Devimon", "evol": "champion", "next": ["bluemeramon", "infermon", "metalgreymon-blue", "myotismon", "kimeramon"], "tribe": "abyss", "skills": [["abyss", 1]], "v2": 0},
	"diaboromon": {"name": "Diaboromon", "evol": "mega", "next": ["armageddemon"], "tribe": "abyss", "skills": [["blazing", 2, "B"]], "v2": 0},
	"dianamon": {"name": "Dianamon", "evol": "mega", "next": [], "tribe": "glacier", "skills": [["bright", 1, "B"]], "v2": 1},
	"digitamamon": {"name": "Digitamamon", "evol": "ultimate", "next": ["minervamon", "belphemon-sm", "titamon"], "tribe": "mirage", "skills": [["mirage", 1]], "v2": 0},
	"dorugamon": {"name": "Dorugamon", "evol": "champion", "next": ["rizegreymon", "dorugreymon", "chirinmon"], "tribe": "mirage", "skills": [["mirage", 1]], "v2": 0},
	"dorugreymon": {"name": "DoruGreymon", "evol": "ultimate", "next": ["alphamon", "kentaurosmon"], "tribe": "mirage", "skills": [["earth", 1]], "v2": 0},
	"dorumon": {"name": "Dorumon", "evol": "rookie", "next": ["cyclonemon", "dorugamon", "guardromon", "waspmon"], "tribe": "mirage", "skills": [["mirage", 1]], "v2": 0},
	"dracomon": {"name": "Dracomon", "evol": "rookie", "next": ["coredramon-blue", "coredramon-green"], "tribe": "mirage", "skills": [["blazing", 1]], "v2": 0},
	"duramon": {"name": "Duramon", "evol": "ultimate", "next": ["durandamon"], "tribe": "mirage", "skills": [["mirage", 1]], "v2": 0},
	"durandamon": {"name": "Durandamon", "evol": "mega", "next": [], "tribe": "mirage", "skills": [["mirage", 1, "S"]], "v2": 0},
	"dynasmon": {"name": "Dynasmon", "evol": "mega", "next": ["dynasmon-x"], "tribe": "mirage", "skills": [["earth", 2, "B"], ["mirage", 1, "SS"]], "v2": 0},
	"dynasmon-x": {"name": "Dynasmon X", "evol": "mega", "next": [], "tribe": "mirage", "skills": [["earth", 1]], "v2": 0},
	"ebemon": {"name": "Ebemon", "evol": "mega", "next": [], "tribe": "electric", "skills": [["electric", 1, "A"]], "v2": 1},
	"elecmon": {"name": "Elecmon", "evol": "rookie", "next": ["garurumon", "leomon", "nanimon", "sukamon", "garurumon-black", "geremon"], "tribe": "electric", "skills": [["electric", 1]], "v2": 0},
	"etemon": {"name": "Etemon", "evol": "ultimate", "next": ["metaletemon", "piedmon", "platinumnumemon", "kingetemon"], "tribe": "abyss", "skills": [["abyss", 1]], "v2": 0},
	"examon": {"name": "Examon", "evol": "mega", "next": [], "tribe": "blazing", "skills": [["electric", 2, "GOD"], ["blazing", 2, "A"]], "v2": 0},
	"exveemon": {"name": "ExVeemon", "evol": "champion", "next": ["magnaangemon", "paildramon", "rizegreymon"], "tribe": "mirage", "skills": [["bright", 1]], "v2": 0},
	"falcomon": {"name": "Falcomon", "evol": "rookie", "next": ["stingmon", "exveemon", "aquilamon", "peckmon"], "tribe": "mirage", "skills": [["earth", 1]], "v2": 0},
	"flamedramon": {"name": "Flamedramon", "evol": "champion", "next": [], "tribe": "blazing", "skills": [["blazing", 1]], "v2": 0},
	"frigimon": {"name": "Frigimon", "evol": "champion", "next": ["zudomon", "angewomon", "monzaemon"], "tribe": "glacier", "skills": [["glacier", 1]], "v2": 0},
	"gabumon": {"name": "Gabumon", "evol": "rookie", "next": ["dorugamon", "garurumon", "numemon", "veedramon", "frigimon"], "tribe": "blazing", "skills": [["blazing", 1]], "v2": 0},
	"gabumon-black": {"name": "Gabumon (Black)", "evol": "rookie", "next": ["garurumon-black", "vegiemon", "reppamon", "frigimon"], "tribe": "blazing", "skills": [["mirage", 1]], "v2": 0},
	"gaiomon": {"name": "Gaiomon", "evol": "mega", "next": ["susanoomon"], "tribe": "blazing", "skills": [["blazing", 1, "A"]], "v2": 0},
	"gallantmon": {"name": "Gallantmon", "evol": "mega", "next": ["gallantmon-cm", "gallantmon-x"], "tribe": "bright", "skills": [["bright", 1, "A"], ["bright", 2, "B"]], "v2": 0},
	"gallantmon-cm": {"name": "Gallantmon CM", "evol": "mega", "next": [], "tribe": "blazing", "skills": [["bright", 1, "SS"]], "v2": 0},
	"gallantmon-x": {"name": "Gallantmon X", "evol": "mega", "next": [], "tribe": "bright", "skills": [["bright", 1, "SS"]], "v2": 0},
	"gankoomon": {"name": "Gankoomon", "evol": "mega", "next": [], "tribe": "blazing", "skills": [["blazing", 1, "SSS"], ["earth", 2, "B"]], "v2": 0},
	"gaogamon": {"name": "GaoGamon", "evol": "champion", "next": ["grapleomon", "machgaogamon", "weregarurumon"], "tribe": "earth", "skills": [["earth", 1]], "v2": 0},
	"gaomon": {"name": "Gaomon", "evol": "rookie", "next": ["gargomon", "gaogamon", "leomon", "togemon", "ogremon"], "tribe": "blazing", "skills": [["mirage", 1]], "v2": 0},
	"gargomon": {"name": "Gargomon", "evol": "champion", "next": ["wargrowlmon", "antylamon", "rapidmon"], "tribe": "electric", "skills": [["mirage", 1]], "v2": 0},
	"garudamon": {"name": "Garudamon", "evol": "ultimate", "next": ["phoenixmon", "justimon", "ravemon"], "tribe": "blazing", "skills": [["blazing", 1]], "v2": 0},
	"garurumon": {"name": "Garurumon", "evol": "champion", "next": ["dorugreymon", "iceleomon", "weregarurumon", "zudomon", "kimeramon"], "tribe": "blazing", "skills": [["blazing", 1]], "v2": 0},
	"garurumon-black": {"name": "Garurumon (Black)", "evol": "champion", "next": ["weregarurumon-black", "bluemeramon", "machgaogamon"], "tribe": "blazing", "skills": [["glacier", 1]], "v2": 0},
	"gatomon": {"name": "Gatomon", "evol": "champion", "next": ["angewomon", "lillymon", "silphymon"], "tribe": "bright", "skills": [["mirage", 1]], "v2": 0},
	"gazimon": {"name": "Gazimon", "evol": "rookie", "next": ["dorugamon", "gaogamon", "leomon", "chrysalimon", "nanimon", "garurumon-black"], "tribe": "abyss", "skills": [["mirage", 1]], "v2": 0},
	"gekomon": {"name": "Gekomon", "evol": "champion", "next": ["megaseadramon", "shogungekomon", "whamon"], "tribe": "glacier", "skills": [["mirage", 1]], "v2": 0},
	"geogreymon": {"name": "GeoGreymon", "evol": "champion", "next": ["gigadramon", "rizegreymon", "skullgreymon"], "tribe": "blazing", "skills": [["blazing", 1]], "v2": 0},
	"geremon": {"name": "Geremon", "evol": "champion", "next": ["etemon", "superstarmon", "metalmamemon"], "tribe": "electric", "skills": [["earth", 1]], "v2": 0},
	"gigadramon": {"name": "Gigadramon", "evol": "ultimate", "next": ["metalseadramon", "machinedramon", "groundlocomon"], "tribe": "electric", "skills": [["blazing", 1]], "v2": 0},
	"goblimon": {"name": "Goblimon", "evol": "rookie", "next": ["gaogamon", "growlmon", "nanimon", "ogremon", "greymon-blue"], "tribe": "earth", "skills": [["blazing", 1]], "v2": 0},
	"goldnumemon": {"name": "GoldNumemon", "evol": "champion", "next": ["vademon", "platinumnumemon", "blackkingnumemon"], "tribe": "bright", "skills": [["bright", 2]], "v2": 0},
	"gomamon": {"name": "Gomamon", "evol": "rookie", "next": ["ankylomon", "ikkakumon", "sorcermon", "frigimon"], "tribe": "glacier", "skills": [["glacier", 1]], "v2": 0},
	"gotsumon": {"name": "Gotsumon", "evol": "rookie", "next": ["ankylomon", "clockmon", "starmon", "tankmon"], "tribe": "mirage", "skills": [["earth", 1]], "v2": 0},
	"grankuwagamon": {"name": "GranKuwagamon", "evol": "mega", "next": [], "tribe": "mirage", "skills": [["earth", 1, "A*"]], "v2": 1},
	"grapleomon": {"name": "GrapLeomon", "evol": "ultimate", "next": ["bancholeomon", "leopardmon", "saberleomon"], "tribe": "electric", "skills": [["earth", 1]], "v2": 0},
	"greymon": {"name": "Greymon", "evol": "champion", "next": ["metalgreymon", "metalgreymon-blue", "megadramon", "skullgreymon", "kimeramon"], "tribe": "blazing", "skills": [["blazing", 1]], "v2": 0},
	"greymon-blue": {"name": "Greymon (Blue)", "evol": "champion", "next": ["metalgreymon-blue", "knightmon", "dorugreymon"], "tribe": "blazing", "skills": [["blazing", 1]], "v2": 0},
	"groundlocomon": {"name": "GroundLocomon", "evol": "mega", "next": [], "tribe": "electric", "skills": [["earth", 2, "C"], ["earth", 1, "B"]], "v2": 1},
	"groundramon": {"name": "Groundramon", "evol": "ultimate", "next": ["brakedramon"], "tribe": "earth", "skills": [["earth", 1]], "v2": 0},
	"growlmon": {"name": "Growlmon", "evol": "champion", "next": ["gigadramon", "wargrowlmon", "metalgreymon", "metaltyrannomon"], "tribe": "blazing", "skills": [["blazing", 1]], "v2": 0},
	"guardromon": {"name": "Guardromon", "evol": "champion", "next": ["andromon", "grapleomon", "metalmamemon", "datamon"], "tribe": "electric", "skills": [["blazing", 1]], "v2": 0},
	"guilmon": {"name": "Guilmon", "evol": "rookie", "next": ["geogreymon", "growlmon", "meramon", "tyrannomon", "greymon-blue"], "tribe": "blazing", "skills": [["earth", 1]], "v2": 0},
	"gumdramon": {"name": "Gumdramon", "evol": "rookie", "next": ["arresterdramon"], "tribe": "blazing", "skills": [["blazing", 1]], "v2": 0},
	"hackmon": {"name": "Hackmon", "evol": "rookie", "next": ["jesmon", "greymon", "geogreymon", "platinumsukamon"], "tribe": "blazing", "skills": [["earth", 1]], "v2": 0},
	"hagurumon": {"name": "Hagurumon", "evol": "rookie", "next": ["clockmon", "goldnumemon", "guardromon", "starmon", "platinumsukamon"], "tribe": "electric", "skills": [["abyss", 1]], "v2": 0},
	"hawkmon": {"name": "Hawkmon", "evol": "rookie", "next": ["meramon", "aquilamon", "birdramon", "peckmon"], "tribe": "mirage", "skills": [["earth", 1]], "v2": 0},
	"herculeskabuterimon": {"name": "HerculesKabuterimon", "evol": "mega", "next": [], "tribe": "earth", "skills": [["electric", 1, "B"]], "v2": 1},
	"hiandromon": {"name": "HiAndromon", "evol": "mega", "next": [], "tribe": "electric", "skills": [["electric", 1, "B"]], "v2": 1},
	"icedevimon": {"name": "IceDevimon", "evol": "champion", "next": ["myotismon", "cherrymon", "ladydevimon"], "tribe": "glacier", "skills": [["glacier", 1]], "v2": 0},
	"iceleomon": {"name": "IceLeomon", "evol": "ultimate", "next": ["bancholeomon", "saberleomon", "miragegaogamon"], "tribe": "glacier", "skills": [["glacier", 1]], "v2": 0},
	"ikkakumon": {"name": "Ikkakumon", "evol": "champion", "next": ["machgaogamon", "whamon", "zudomon"], "tribe": "glacier", "skills": [["blazing", 1]], "v2": 0},
	"imperialdramon-dm": {"name": "Imperialdramon DM", "evol": "mega", "next": ["imperialdramon-fm"], "tribe": "blazing", "skills": [["abyss", 2, "D"]], "v2": 0},
	"imperialdramon-fm": {"name": "Imperialdramon FM", "evol": "mega", "next": ["imperialdramon-pm", "imperialdramon-dm"], "tribe": "mirage", "skills": [["bright", 1, "B"]], "v2": 0},
	"imperialdramon-pm": {"name": "Imperialdramon PM", "evol": "mega", "next": [], "tribe": "bright", "skills": [["mirage", 1, "S"]], "v2": 0},
	"impmon": {"name": "Impmon", "evol": "rookie", "next": ["bakemon", "ogremon", "sorcermon", "blackgatomon", "wizardmon", "icedevimon"], "tribe": "abyss", "skills": [["mirage", 1]], "v2": 0},
	"infermon": {"name": "Infermon", "evol": "ultimate", "next": ["beelzemon", "diaboromon", "venommyotismon"], "tribe": "abyss", "skills": [["blazing", 1]], "v2": 0},
	"jesmon": {"name": "Jesmon", "evol": "mega", "next": [], "tribe": "mirage", "skills": [["mirage", 1, "SSS"], ["mirage", 0, "F"]], "v2": 0},
	"justimon": {"name": "Justimon", "evol": "mega", "next": [], "tribe": "bright", "skills": [["mirage", 1, "D*"]], "v2": 1},
	"kabuterimon": {"name": "Kabuterimon", "evol": "champion", "next": ["megakabuterimon", "cherrymon", "lilamon", "kimeramon"], "tribe": "earth", "skills": [["electric", 1]], "v2": 0},
	"kentaurosmon": {"name": "Kentaurosmon", "evol": "mega", "next": [], "tribe": "bright", "skills": [["bright", 1, "A"], ["glacier", 2, "A"]], "v2": 0},
	"keramon": {"name": "Keramon", "evol": "rookie", "next": ["bakemon", "wizardmon", "chrysalimon", "platinumsukamon"], "tribe": "abyss", "skills": [["abyss", 1]], "v2": 0},
	"kimeramon": {"name": "Kimeramon", "evol": "ultimate", "next": ["millenniummon"], "tribe": "mirage", "skills": [["blazing", 1]], "v2": 0},
	"kingetemon": {"name": "KingEtemon", "evol": "mega", "next": [], "tribe": "earth", "skills": [["mirage", 2]], "v2": 0},
	"knightmon": {"name": "Knightmon", "evol": "ultimate", "next": ["craniamon", "leopardmon", "lordknightmon"], "tribe": "mirage", "skills": [["mirage", 1]], "v2": 0},
	"koromon": {"name": "Koromon", "evol": "in-training-ii", "next": ["agumon", "guilmon", "toyagumon", "hackmon", "dracomon", "shoutmon"], "tribe": "mirage", "skills": [["mirage", 1]], "v2": 0},
	"kudamon": {"name": "Kudamon", "evol": "rookie", "next": ["angemon", "goldnumemon", "peckmon", "reppamon"], "tribe": "bright", "skills": [["bright", 1]], "v2": 0},
	"kuramon": {"name": "Kuramon", "evol": "in-training-i", "next": ["tsumemon", "pagumon"], "tribe": "mirage", "skills": [["mirage", 1]], "v2": 0},
	"kuwagamon": {"name": "Kuwagamon", "evol": "champion", "next": ["cherrymon", "okuwamon", "cannonbeemon", "kimeramon"], "tribe": "mirage", "skills": [["mirage", 1]], "v2": 0},
	"kuzuhamon": {"name": "Kuzuhamon", "evol": "mega", "next": [], "tribe": "abyss", "skills": [["abyss", 1, "C"]], "v2": 1},
	"kyubimon": {"name": "Kyubimon", "evol": "champion", "next": ["ladydevimon", "monzaemon", "taomon"], "tribe": "blazing", "skills": [["blazing", 1]], "v2": 0},
	"ladydevimon": {"name": "LadyDevimon", "evol": "ultimate", "next": ["lilithmon", "lotosmon", "mastemon"], "tribe": "abyss", "skills": [["abyss", 2]], "v2": 0},
	"lalamon": {"name": "Lalamon", "evol": "rookie", "next": ["sunflowmon", "togemon", "vegiemon", "woodmon"], "tribe": "earth", "skills": [["glacier", 1]], "v2": 0},
	"lavogaritamon-atk": {"name": "Lavogaritamon (ATK)", "evol": "ultimate", "next": ["volcanicdramon-atk"], "tribe": "blazing", "skills": [["blazing", 1]], "v2": 0},
	"lavogaritamon-bal": {"name": "Lavogaritamon (BAL)", "evol": "ultimate", "next": ["volcanicdramon-bal"], "tribe": "blazing", "skills": [["blazing", 2]], "v2": 0},
	"lavogaritamon-def": {"name": "Lavogaritamon (DEF)", "evol": "ultimate", "next": ["volcanicdramon-def"], "tribe": "blazing", "skills": [["blazing", 2]], "v2": 0},
	"lavogaritamon-satk": {"name": "Lavogaritamon (SATK)", "evol": "ultimate", "next": ["volcanicdramon-satk"], "tribe": "blazing", "skills": [["blazing", 1]], "v2": 0},
	"lavogaritamon-sdef": {"name": "Lavogaritamon (SDEF)", "evol": "ultimate", "next": ["volcanicdramon-sdef"], "tribe": "blazing", "skills": [["blazing", 2]], "v2": 0},
	"lavogaritamon-spd-atk": {"name": "Lavogaritamon (SPD ATK)", "evol": "ultimate", "next": ["volcanicdramon-spd-atk"], "tribe": "blazing", "skills": [["blazing", 1]], "v2": 0},
	"lavogaritamon-spd-satk": {"name": "Lavogaritamon (SPD SATK)", "evol": "ultimate", "next": ["volcanicdramon-spd-satk"], "tribe": "blazing", "skills": [["blazing", 1]], "v2": 0},
	"lavorvomon-blue": {"name": "Lavorvomon (Blue)", "evol": "champion", "next": ["lavogaritamon-spd-atk", "lavogaritamon-spd-satk"], "tribe": "blazing", "skills": [["blazing", 1]], "v2": 0},
	"lavorvomon-green": {"name": "Lavorvomon (Green)", "evol": "champion", "next": ["lavogaritamon-def", "lavogaritamon-sdef"], "tribe": "blazing", "skills": [["blazing", 1]], "v2": 0},
	"lavorvomon-orange": {"name": "Lavorvomon (Orange)", "evol": "champion", "next": ["lavogaritamon-atk", "lavogaritamon-satk"], "tribe": "blazing", "skills": [["blazing", 1]], "v2": 0},
	"lavorvomon-white": {"name": "Lavorvomon (White)", "evol": "champion", "next": ["lavogaritamon-bal"], "tribe": "blazing", "skills": [["blazing", 1]], "v2": 0},
	"leomon": {"name": "Leomon", "evol": "champion", "next": ["grapleomon", "metalgreymon", "meteormon", "iceleomon"], "tribe": "earth", "skills": [["earth", 1]], "v2": 0},
	"leopardmon": {"name": "Leopardmon", "evol": "mega", "next": ["leopardmon-lm"], "tribe": "bright", "skills": [["bright", 2, "A"], ["mirage", 1, "SS"]], "v2": 0},
	"leopardmon-lm": {"name": "Leopardmon LM", "evol": "mega", "next": ["leopardmon"], "tribe": "earth", "skills": [["earth", 1, "SS"]], "v2": 0},
	"leviamon": {"name": "Leviamon", "evol": "mega", "next": [], "tribe": "glacier", "skills": [["glacier", 1, "SS"]], "v2": 0},
	"lilamon": {"name": "Lilamon", "evol": "ultimate", "next": ["lilithmon", "lotosmon", "rosemon"], "tribe": "earth", "skills": [["earth", 2]], "v2": 0},
	"lilithmon": {"name": "Lilithmon", "evol": "mega", "next": [], "tribe": "abyss", "skills": [["abyss", 1, "S"]], "v2": 0},
	"lillymon": {"name": "Lillymon", "evol": "ultimate", "next": ["magnadramon", "lotosmon", "rosemon"], "tribe": "earth", "skills": [["earth", 1]], "v2": 0},
	"lopmon": {"name": "Lopmon", "evol": "rookie", "next": ["gargomon", "devimon", "blackgatomon", "wizardmon"], "tribe": "earth", "skills": [["glacier", 1]], "v2": 0},
	"lordknightmon": {"name": "LordKnightmon", "evol": "mega", "next": [], "tribe": "abyss", "skills": [["abyss", 2, "SSS"], ["blazing", 1, "SS"]], "v2": 0},
	"lotosmon": {"name": "Lotosmon", "evol": "mega", "next": [], "tribe": "earth", "skills": [["bright", 1, "A"]], "v2": 0},
	"lucemon": {"name": "Lucemon", "evol": "rookie", "next": ["angemon", "devimon", "lucemon-fm"], "tribe": "bright", "skills": [["bright", 2]], "v2": 0},
	"lucemon-fm": {"name": "Lucemon FM", "evol": "ultimate", "next": ["lucemon-sm"], "tribe": "mirage", "skills": [["mirage", 1]], "v2": 0},
	"lucemon-sm": {"name": "Lucemon SM", "evol": "mega", "next": [], "tribe": "abyss", "skills": [["bright", 2, "GOD"]], "v2": 0},
	"machgaogamon": {"name": "MachGaogamon", "evol": "ultimate", "next": ["bancholeomon", "miragegaogamon", "megagargomon"], "tribe": "earth", "skills": [["mirage", 1]], "v2": 0},
	"machinedramon": {"name": "Machinedramon", "evol": "mega", "next": ["millenniummon", "chaosdramon"], "tribe": "electric", "skills": [["electric", 2, "SS"]], "v2": 0},
	"magnaangemon": {"name": "MagnaAngemon", "evol": "ultimate", "next": ["shinegreymon", "lordknightmon", "seraphimon"], "tribe": "bright", "skills": [["bright", 2]], "v2": 0},
	"magnadramon": {"name": "Magnadramon", "evol": "mega", "next": [], "tribe": "bright", "skills": [["bright", 2, "C"]], "v2": 1},
	"magnamon": {"name": "Magnamon", "evol": "mega", "next": ["magnamon-x"], "tribe": "mirage", "skills": [["bright", 2, "S"], ["blazing", 2, "S"]], "v2": 0},
	"magnamon-x": {"name": "Magnamon X", "evol": "mega", "next": [], "tribe": "mirage", "skills": [["blazing", 2, "SS"]], "v2": 0},
	"mamemon": {"name": "Mamemon", "evol": "ultimate", "next": ["puppetmon", "princemamemon", "wargreymon"], "tribe": "mirage", "skills": [["blazing", 1]], "v2": 0},
	"marineangemon": {"name": "MarineAngemon", "evol": "mega", "next": [], "tribe": "glacier", "skills": [["mirage", 0, "C"]], "v2": 0},
	"mastemon": {"name": "Mastemon", "evol": "mega", "next": [], "tribe": "mirage", "skills": [["mirage", 2, "B"]], "v2": 1},
	"megadramon": {"name": "Megadramon", "evol": "ultimate", "next": ["blackwargreymon", "machinedramon", "ulforceveedramon"], "tribe": "electric", "skills": [["blazing", 1]], "v2": 0},
	"megagargomon": {"name": "MegaGargomon", "evol": "mega", "next": [], "tribe": "electric", "skills": [["blazing", 2, "SS"]], "v2": 1},
	"megakabuterimon": {"name": "MegaKabuterimon", "evol": "ultimate", "next": ["grankuwagamon", "herculeskabuterimon", "magnadramon"], "tribe": "earth", "skills": [["electric", 1]], "v2": 0},
	"megaseadramon": {"name": "MegaSeadramon", "evol": "ultimate", "next": ["leviamon", "metalseadramon", "plesiomon"], "tribe": "glacier", "skills": [["electric", 1]], "v2": 0},
	"meicoomon": {"name": "Meicoomon", "evol": "champion", "next": ["meicrackmon-vm"], "tribe": "mirage", "skills": [["mirage", 1]], "v2": 0},
	"meicrackmon-vm": {"name": "Meicrackmon VM", "evol": "ultimate", "next": ["raguelmon"], "tribe": "abyss", "skills": [["mirage", 1]], "v2": 0, "special": 1},
	"meramon": {"name": "Meramon", "evol": "champion", "next": ["bluemeramon", "skullmeramon", "mamemon", "iceleomon"], "tribe": "blazing", "skills": [["blazing", 1]], "v2": 0},
	"metaletemon": {"name": "MetalEtemon", "evol": "mega", "next": [], "tribe": "earth", "skills": [["mirage", 2, "F"]], "v2": 1},
	"metalgarurumon": {"name": "MetalGarurumon", "evol": "mega", "next": ["omegamon", "metalgarurumon-x"], "tribe": "electric", "skills": [["glacier", 2, "C"], ["mirage", 1, "C"]], "v2": 0},
	"metalgarurumon-black": {"name": "MetalGarurumon (Black)", "evol": "mega", "next": ["omegamon-zwart"], "tribe": "electric", "skills": [["glacier", 2, "C"], ["mirage", 1, "B"]], "v2": 0},
	"metalgarurumon-x": {"name": "MetalGarurumon X", "evol": "mega", "next": [], "tribe": "electric", "skills": [["glacier", 1, "S"]], "v2": 0},
	"metalgreymon": {"name": "MetalGreymon", "evol": "ultimate", "next": ["rusttyranomon", "gaiomon", "wargreymon", "ancientgreymon", "blitzgreymon"], "tribe": "blazing", "skills": [["blazing", 1]], "v2": 0},
	"metalgreymon-blue": {"name": "MetalGreymon (Blue)", "evol": "ultimate", "next": ["wargreymon", "gaiomon", "blackwargreymon"], "tribe": "blazing", "skills": [["mirage", 0]], "v2": 0},
	"metalmamemon": {"name": "MetalMamemon", "evol": "ultimate", "next": ["ebemon", "hiandromon", "princemamemon"], "tribe": "electric", "skills": [["electric", 1]], "v2": 0},
	"metalseadramon": {"name": "MetalSeadramon", "evol": "mega", "next": [], "tribe": "glacier", "skills": [["glacier", 1, "C"]], "v2": 1},
	"metaltyrannomon": {"name": "MetalTyrannomon", "evol": "ultimate", "next": ["blackwargreymon", "gallantmon", "rusttyranomon"], "tribe": "electric", "skills": [["electric", 1]], "v2": 0},
	"meteormon": {"name": "Meteormon", "evol": "ultimate", "next": ["ebemon", "metaletemon", "dianamon", "metalgarurumon"], "tribe": "mirage", "skills": [["mirage", 2]], "v2": 0},
	"millenniummon": {"name": "Millenniummon", "evol": "mega", "next": [], "tribe": "mirage", "skills": [["bright", 2, "SSS"]], "v2": 0},
	"minervamon": {"name": "Minervamon", "evol": "mega", "next": [], "tribe": "mirage", "skills": [["mirage", 1, "B*"]], "v2": 1},
	"miragegaogamon": {"name": "MirageGaogamon", "evol": "mega", "next": ["omegamon-zwart-d", "miragegaogamon-bm"], "tribe": "bright", "skills": [["bright", 1, "B"]], "v2": 0},
	"miragegaogamon-bm": {"name": "MirageGaogamon BM", "evol": "mega", "next": [], "tribe": "bright", "skills": [["bright", 1, "A"]], "v2": 0},
	"monzaemon": {"name": "Monzaemon", "evol": "ultimate", "next": ["minervamon", "sakuyamon", "saberleomon"], "tribe": "mirage", "skills": [["mirage", 1]], "v2": 0},
	"motimon": {"name": "Motimon", "evol": "in-training-ii", "next": ["gotsumon", "solarmon", "tentomon", "hagurumon"], "tribe": "mirage", "skills": [["mirage", 1]], "v2": 0},
	"myotismon": {"name": "Myotismon", "evol": "ultimate", "next": ["barbamon", "piedmon", "venommyotismon"], "tribe": "abyss", "skills": [["abyss", 1]], "v2": 0},
	"nanimon": {"name": "Nanimon", "evol": "champion", "next": ["digitamamon", "superstarmon", "meteormon"], "tribe": "mirage", "skills": [["earth", 1]], "v2": 0},
	"numemon": {"name": "Numemon", "evol": "champion", "next": ["blackkingnumemon", "etemon", "monzaemon"], "tribe": "glacier", "skills": [["earth", 1]], "v2": 0},
	"nyaromon": {"name": "Nyaromon", "evol": "in-training-ii", "next": ["armadillomon", "terriermon", "salamon"], "tribe": "mirage", "skills": [["mirage", 1]], "v2": 0},
	"ogremon": {"name": "Ogremon", "evol": "champion", "next": ["skullmeramon", "digitamamon", "weregarurumon"], "tribe": "earth", "skills": [["abyss", 1]], "v2": 0},
	"okuwamon": {"name": "Okuwamon", "evol": "ultimate", "next": ["diaboromon", "grankuwagamon", "herculeskabuterimon"], "tribe": "mirage", "skills": [["mirage", 1]], "v2": 0},
	"omega-shoutmon": {"name": "Omega Shoutmon", "evol": "mega", "next": [], "tribe": "electric", "skills": [["blazing", 1]], "v2": 0},
	"omegamon": {"name": "Omegamon", "evol": "mega", "next": ["omegamon-x", "omegamon-mm"], "tribe": "bright", "skills": [["blazing", 2, "B"], ["glacier", 1, "SS"]], "v2": 0},
	"omegamon-alter-b": {"name": "Omegamon Alter-B", "evol": "mega", "next": [], "tribe": "abyss", "skills": [["abyss", 1, "SSS"]], "v2": 0},
	"omegamon-alter-s": {"name": "Omegamon Alter-S", "evol": "mega", "next": [], "tribe": "bright", "skills": [["mirage", 1], ["electric", 1]], "v2": 0},
	"omegamon-mm": {"name": "Omegamon MM", "evol": "mega", "next": [], "tribe": "bright", "skills": [["mirage", 2]], "v2": 0},
	"omegamon-x": {"name": "Omegamon X", "evol": "mega", "next": [], "tribe": "bright", "skills": [["mirage", 2]], "v2": 0},
	"omegamon-zwart": {"name": "Omegamon Zwart", "evol": "mega", "next": [], "tribe": "abyss", "skills": [["blazing", 2, "B"], ["glacier", 1, "SS"]], "v2": 0},
	"omegamon-zwart-d": {"name": "Omegamon Zwart D", "evol": "mega", "next": ["omegamon-alter-b"], "tribe": "abyss", "skills": [["abyss", 1, "A"]], "v2": 0},
	"ophanimon": {"name": "Ophanimon", "evol": "mega", "next": [], "tribe": "bright", "skills": [["bright", 1, "A"]], "v2": 0},
	"ophanimon-fm": {"name": "Ophanimon FM", "evol": "mega", "next": [], "tribe": "abyss", "skills": [["blazing", 1, "A"]], "v2": 0},
	"otamamon": {"name": "Otamamon", "evol": "rookie", "next": ["gekomon", "numemon", "seadramon", "shellnumemon"], "tribe": "glacier", "skills": [["glacier", 1]], "v2": 0},
	"pabumon": {"name": "Pabumon", "evol": "in-training-i", "next": ["tanemon", "yokomon", "motimon"], "tribe": "mirage", "skills": [["mirage", 1]], "v2": 0},
	"pagumon": {"name": "Pagumon", "evol": "in-training-ii", "next": ["impmon", "gazimon", "lopmon"], "tribe": "mirage", "skills": [["mirage", 1]], "v2": 0},
	"paildramon": {"name": "Paildramon", "evol": "ultimate", "next": ["imperialdramon-dm"], "tribe": "mirage", "skills": [["blazing", 1]], "v2": 0},
	"palmon": {"name": "Palmon", "evol": "rookie", "next": ["kuwagamon", "togemon", "vegiemon", "sunflowmon", "woodmon"], "tribe": "earth", "skills": [["mirage", 1]], "v2": 0},
	"patamon": {"name": "Patamon", "evol": "rookie", "next": ["angemon", "birdramon", "reppamon", "gatomon", "exveemon"], "tribe": "bright", "skills": [["earth", 1]], "v2": 0},
	"peckmon": {"name": "Peckmon", "evol": "champion", "next": ["antylamon", "piximon", "crowmon"], "tribe": "mirage", "skills": [["earth", 1]], "v2": 0},
	"phoenixmon": {"name": "Phoenixmon", "evol": "mega", "next": [], "tribe": "blazing", "skills": [["blazing", 2, "C"]], "v2": 1},
	"piedmon": {"name": "Piedmon", "evol": "mega", "next": [], "tribe": "abyss", "skills": [["mirage", 1, "SS"]], "v2": 0},
	"piximon": {"name": "Piximon", "evol": "ultimate", "next": ["cherubimon-good", "marineangemon", "ophanimon"], "tribe": "bright", "skills": [["blazing", 1]], "v2": 0},
	"platinumnumemon": {"name": "PlatinumNumemon", "evol": "mega", "next": [], "tribe": "mirage", "skills": [["earth", 1, "B*"]], "v2": 1},
	"platinumsukamon": {"name": "PlatinumSukamon", "evol": "champion", "next": ["etemon", "metalmamemon", "vademon"], "tribe": "mirage", "skills": [["earth", 1]], "v2": 0},
	"plesiomon": {"name": "Plesiomon", "evol": "mega", "next": [], "tribe": "glacier", "skills": [["glacier", 1, "A"]], "v2": 0},
	"poyomon": {"name": "Poyomon", "evol": "in-training-i", "next": ["tokomon", "bukamon"], "tribe": "mirage", "skills": [["mirage", 1]], "v2": 0},
	"princemamemon": {"name": "PrinceMamemon", "evol": "mega", "next": [], "tribe": "mirage", "skills": [["mirage", 1, "B*"]], "v2": 1},
	"pumpkinmon": {"name": "Pumpkinmon", "evol": "ultimate", "next": ["boltmon", "puppetmon", "rosemon"], "tribe": "earth", "skills": [["mirage", 1]], "v2": 0},
	"punimon": {"name": "Punimon", "evol": "in-training-i", "next": ["tsunomon", "nyaromon"], "tribe": "mirage", "skills": [["mirage", 1]], "v2": 0},
	"puppetmon": {"name": "Puppetmon", "evol": "mega", "next": [], "tribe": "earth", "skills": [["earth", 1, "C"]], "v2": 1},
	"raguelmon": {"name": "Raguelmon", "evol": "mega", "next": [], "tribe": "abyss", "skills": [["mirage", 1, "S"]], "v2": 0},
	"rapidmon": {"name": "Rapidmon", "evol": "ultimate", "next": ["megagargomon", "tigervespamon", "metalgarurumon-black"], "tribe": "electric", "skills": [["electric", 1]], "v2": 0},
	"rapidmon-gold": {"name": "Rapidmon (Gold)", "evol": "champion", "next": [], "tribe": "bright", "skills": [["bright", 1]], "v2": 0},
	"ravemon": {"name": "Ravemon", "evol": "mega", "next": ["ravemon-bm"], "tribe": "electric", "skills": [["electric", 2, "D"]], "v2": 0},
	"ravemon-bm": {"name": "Ravemon BM", "evol": "mega", "next": [], "tribe": "electric", "skills": [["earth", 1, "SSS"]], "v2": 0},
	"renamon": {"name": "Renamon", "evol": "rookie", "next": ["blackgatomon", "garurumon", "kyubimon", "woodmon"], "tribe": "bright", "skills": [["earth", 1]], "v2": 0},
	"reppamon": {"name": "Reppamon", "evol": "champion", "next": ["rapidmon", "piximon", "chirinmon"], "tribe": "bright", "skills": [["mirage", 1]], "v2": 0},
	"rizegreymon": {"name": "RizeGreymon", "evol": "ultimate", "next": ["gaiomon", "shinegreymon"], "tribe": "blazing", "skills": [["blazing", 1]], "v2": 0},
	"rosemon": {"name": "Rosemon", "evol": "mega", "next": ["rosemon-bm"], "tribe": "earth", "skills": [["earth", 1, "A"]], "v2": 0},
	"rosemon-bm": {"name": "Rosemon BM", "evol": "mega", "next": [], "tribe": "earth", "skills": [["earth", 1, "S"]], "v2": 0},
	"rusttyranomon": {"name": "RustTyranomon", "evol": "mega", "next": [], "tribe": "electric", "skills": [["electric", 1, "A"]], "v2": 1},
	"saberleomon": {"name": "SaberLeomon", "evol": "mega", "next": [], "tribe": "earth", "skills": [["earth", 1, "B"]], "v2": 1},
	"sakuyamon": {"name": "Sakuyamon", "evol": "mega", "next": [], "tribe": "bright", "skills": [["bright", 1, "B"]], "v2": 1},
	"salamon": {"name": "Salamon", "evol": "rookie", "next": ["frigimon", "reppamon", "gatomon", "veedramon", "sorcermon", "meicoomon"], "tribe": "bright", "skills": [["bright", 1]], "v2": 0},
	"seadramon": {"name": "Seadramon", "evol": "champion", "next": ["shogungekomon", "megaseadramon", "whamon"], "tribe": "glacier", "skills": [["glacier", 1]], "v2": 0},
	"seraphimon": {"name": "Seraphimon", "evol": "mega", "next": [], "tribe": "bright", "skills": [["bright", 2, "SS"]], "v2": 0},
	"shakkoumon": {"name": "Shakkoumon", "evol": "ultimate", "next": ["cherubimon-good", "vikemon", "seraphimon"], "tribe": "bright", "skills": [["bright", 1]], "v2": 0},
	"shellnumemon": {"name": "ShellNumemon", "evol": "champion", "next": ["blackkingnumemon", "megaseadramon", "shogungekomon"], "tribe": "glacier", "skills": [["earth", 1]], "v2": 0},
	"shinegreymon": {"name": "ShineGreymon", "evol": "mega", "next": ["omegamon-zwart-d", "shinegreymon-bm", "shinegreymon-rm"], "tribe": "bright", "skills": [["blazing", 1, "B"]], "v2": 0},
	"shinegreymon-bm": {"name": "ShineGreymon BM", "evol": "mega", "next": [], "tribe": "blazing", "skills": [["blazing", 2, "B"]], "v2": 0},
	"shinegreymon-rm": {"name": "ShineGreymon RM", "evol": "mega", "next": [], "tribe": "abyss", "skills": [["abyss", 2, "B"]], "v2": 0},
	"shogungekomon": {"name": "ShogunGekomon", "evol": "ultimate", "next": ["plesiomon", "leviamon", "vikemon"], "tribe": "glacier", "skills": [["mirage", 1]], "v2": 0},
	"shoutmon": {"name": "Shoutmon", "evol": "rookie", "next": ["omega-shoutmon"], "tribe": "electric", "skills": [["blazing", 1]], "v2": 0},
	"silphymon": {"name": "Silphymon", "evol": "ultimate", "next": ["dynasmon", "phoenixmon", "sakuyamon"], "tribe": "electric", "skills": [["earth", 1]], "v2": 0},
	"skullgreymon": {"name": "SkullGreymon", "evol": "ultimate", "next": ["creepymon", "shinegreymon", "titamon"], "tribe": "abyss", "skills": [["blazing", 2]], "v2": 0},
	"skullmeramon": {"name": "SkullMeramon", "evol": "ultimate", "next": ["gankoomon", "beelzemon", "boltmon"], "tribe": "blazing", "skills": [["blazing", 1]], "v2": 0},
	"slayerdramon": {"name": "Slayerdramon", "evol": "mega", "next": ["examon"], "tribe": "blazing", "skills": [["blazing", 1, "B"]], "v2": 0},
	"solarmon": {"name": "Solarmon", "evol": "rookie", "next": ["clockmon", "geremon", "starmon", "meramon"], "tribe": "bright", "skills": [["bright", 1]], "v2": 0},
	"sorcermon": {"name": "Sorcermon", "evol": "champion", "next": ["antylamon", "piximon", "wisemon"], "tribe": "glacier", "skills": [["glacier", 1]], "v2": 0},
	"starmon": {"name": "Starmon", "evol": "champion", "next": ["mamemon", "metalmamemon", "superstarmon"], "tribe": "bright", "skills": [["mirage", 2]], "v2": 0},
	"stingmon": {"name": "Stingmon", "evol": "champion", "next": ["infermon", "paildramon", "okuwamon"], "tribe": "earth", "skills": [["glacier", 1]], "v2": 0},
	"sukamon": {"name": "Sukamon", "evol": "champion", "next": ["superstarmon", "etemon", "vademon"], "tribe": "mirage", "skills": [["earth", 1]], "v2": 0},
	"sunflowmon": {"name": "Sunflowmon", "evol": "champion", "next": ["angewomon", "lilamon", "lillymon"], "tribe": "earth", "skills": [["bright", 2]], "v2": 0},
	"superstarmon": {"name": "SuperStarmon", "evol": "ultimate", "next": ["justimon", "gankoomon", "platinumnumemon"], "tribe": "bright", "skills": [["bright", 1]], "v2": 0},
	"susanoomon": {"name": "Susanoomon", "evol": "mega", "next": [], "tribe": "bright", "skills": [["bright", 1, "SS"]], "v2": 0},
	"syakomon": {"name": "Syakomon", "evol": "rookie", "next": ["ikkakumon", "shellnumemon", "gekomon", "seadramon"], "tribe": "glacier", "skills": [["glacier", 1]], "v2": 0},
	"tanemon": {"name": "Tanemon", "evol": "in-training-ii", "next": ["palmon", "lalamon", "renamon"], "tribe": "mirage", "skills": [["mirage", 1]], "v2": 0},
	"tankmon": {"name": "Tankmon", "evol": "champion", "next": ["andromon", "gigadramon", "cannonbeemon", "knightmon"], "tribe": "electric", "skills": [["blazing", 1]], "v2": 0},
	"taomon": {"name": "Taomon", "evol": "ultimate", "next": ["dianamon", "kuzuhamon", "sakuyamon", "phoenixmon"], "tribe": "abyss", "skills": [["abyss", 1]], "v2": 0},
	"tentomon": {"name": "Tentomon", "evol": "rookie", "next": ["kabuterimon", "waspmon", "kuwagamon", "stingmon", "sunflowmon"], "tribe": "electric", "skills": [["electric", 1]], "v2": 0},
	"terriermon": {"name": "Terriermon", "evol": "rookie", "next": ["gargomon", "ikkakumon", "gatomon", "rapidmon-gold"], "tribe": "earth", "skills": [["earth", 1]], "v2": 0},
	"tigervespamon": {"name": "TigerVespamon", "evol": "mega", "next": [], "tribe": "electric", "skills": [["electric", 1, "SS"]], "v2": 0},
	"titamon": {"name": "Titamon", "evol": "mega", "next": [], "tribe": "earth", "skills": [["earth", 1, "B"]], "v2": 1},
	"togemon": {"name": "Togemon", "evol": "champion", "next": ["machgaogamon", "lillymon", "pumpkinmon"], "tribe": "earth", "skills": [["earth", 2]], "v2": 0},
	"tokomon": {"name": "Tokomon", "evol": "in-training-ii", "next": ["patamon", "falcomon", "hawkmon", "lucemon"], "tribe": "mirage", "skills": [["mirage", 1]], "v2": 0},
	"toyagumon": {"name": "ToyAgumon", "evol": "rookie", "next": ["clockmon", "greymon", "guardromon", "sukamon", "starmon"], "tribe": "electric", "skills": [["blazing", 1]], "v2": 0},
	"tsumemon": {"name": "Tsumemon", "evol": "in-training-ii", "next": ["agumon-black", "keramon", "demidevimon"], "tribe": "mirage", "skills": [["mirage", 1]], "v2": 0},
	"tsunomon": {"name": "Tsunomon", "evol": "in-training-ii", "next": ["gabumon", "gabumon-black", "goblimon", "veemon", "gumdramon", "zubamon"], "tribe": "mirage", "skills": [["mirage", 1]], "v2": 0},
	"tyrannomon": {"name": "Tyrannomon", "evol": "champion", "next": ["mamemon", "megadramon", "metalgreymon-blue", "metaltyrannomon"], "tribe": "blazing", "skills": [["blazing", 2]], "v2": 0},
	"ulforceveedramon": {"name": "UlforceVeedramon", "evol": "mega", "next": ["ulforceveedramon-x"], "tribe": "bright", "skills": [["bright", 2, "A"], ["earth", 1, "SSS"]], "v2": 0},
	"ulforceveedramon-x": {"name": "UlforceVeedramon X", "evol": "mega", "next": [], "tribe": "bright", "skills": [["bright", 2]], "v2": 0},
	"vademon": {"name": "Vademon", "evol": "ultimate", "next": ["ebemon", "herculeskabuterimon", "hiandromon"], "tribe": "abyss", "skills": [["abyss", 1]], "v2": 0},
	"veedramon": {"name": "Veedramon", "evol": "champion", "next": ["aeroveedramon", "cyberdramon", "metaltyrannomon", "wargrowlmon"], "tribe": "mirage", "skills": [["blazing", 1]], "v2": 0},
	"veemon": {"name": "Veemon", "evol": "rookie", "next": ["flamedramon", "magnamon", "veedramon", "exveemon"], "tribe": "mirage", "skills": [["mirage", 1]], "v2": 0},
	"vegiemon": {"name": "Vegiemon", "evol": "champion", "next": ["digitamamon", "lilamon", "megakabuterimon"], "tribe": "earth", "skills": [["earth", 1]], "v2": 0},
	"venommyotismon": {"name": "VenomMyotismon", "evol": "mega", "next": [], "tribe": "abyss", "skills": [["abyss", 1, "A"]], "v2": 0},
	"vikemon": {"name": "Vikemon", "evol": "mega", "next": [], "tribe": "glacier", "skills": [["glacier", 1, "B"]], "v2": 1},
	"volcanicdramon-atk": {"name": "Volcanicdramon (ATK)", "evol": "mega", "next": [], "tribe": "blazing", "skills": [["blazing", 1, "SS"]], "v2": 0},
	"volcanicdramon-bal": {"name": "Volcanicdramon (BAL)", "evol": "mega", "next": [], "tribe": "blazing", "skills": [["blazing", 2, "SS"]], "v2": 0},
	"volcanicdramon-def": {"name": "Volcanicdramon (DEF)", "evol": "mega", "next": [], "tribe": "blazing", "skills": [["blazing", 2, "B"]], "v2": 0},
	"volcanicdramon-satk": {"name": "Volcanicdramon (SATK)", "evol": "mega", "next": [], "tribe": "blazing", "skills": [["blazing", 1, "SS"]], "v2": 0},
	"volcanicdramon-sdef": {"name": "Volcanicdramon (SDEF)", "evol": "mega", "next": [], "tribe": "blazing", "skills": [["blazing", 2, "B"]], "v2": 0},
	"volcanicdramon-spd-atk": {"name": "Volcanicdramon (SPD ATK)", "evol": "mega", "next": [], "tribe": "blazing", "skills": [["blazing", 1, "A"]], "v2": 0},
	"volcanicdramon-spd-satk": {"name": "Volcanicdramon (SPD SATK)", "evol": "mega", "next": [], "tribe": "blazing", "skills": [["blazing", 1, "A"]], "v2": 0},
	"vorvomon": {"name": "Vorvomon", "evol": "rookie", "next": ["lavorvomon-orange", "lavorvomon-green", "lavorvomon-white", "lavorvomon-blue"], "tribe": "blazing", "skills": [["blazing", 1]], "v2": 0},
	"wanyamon": {"name": "Wanyamon", "evol": "in-training-ii", "next": ["gaomon", "kudamon", "dorumon"], "tribe": "mirage", "skills": [["mirage", 1]], "v2": 0},
	"wargreymon": {"name": "WarGreymon", "evol": "mega", "next": ["omegamon", "wargreymon-x"], "tribe": "blazing", "skills": [["blazing", 2, "C"], ["blazing", 1, "B"]], "v2": 0},
	"wargreymon-x": {"name": "WarGreymon X", "evol": "mega", "next": [], "tribe": "blazing", "skills": [["glacier", 1, "S"]], "v2": 0},
	"wargrowlmon": {"name": "WarGrowlmon", "evol": "ultimate", "next": ["gallantmon", "chaosgallantmon", "rusttyranomon"], "tribe": "blazing", "skills": [["electric", 1]], "v2": 0},
	"waspmon": {"name": "Waspmon", "evol": "champion", "next": ["cannonbeemon", "rapidmon", "megakabuterimon", "okuwamon"], "tribe": "electric", "skills": [["electric", 1]], "v2": 0},
	"weregarurumon": {"name": "WereGarurumon", "evol": "ultimate", "next": ["metalgarurumon", "metalgarurumon-black", "miragegaogamon", "ancientgarurumon", "cresgarurumon"], "tribe": "earth", "skills": [["mirage", 1]], "v2": 0},
	"weregarurumon-black": {"name": "WereGarurumon (Black)", "evol": "ultimate", "next": ["metalgarurumon-black", "minervamon", "bancholeomon"], "tribe": "earth", "skills": [["earth", 1]], "v2": 0},
	"whamon": {"name": "Whamon", "evol": "ultimate", "next": ["plesiomon", "marineangemon", "metalseadramon"], "tribe": "glacier", "skills": [["glacier", 2]], "v2": 0},
	"wingdramon": {"name": "Wingdramon", "evol": "ultimate", "next": ["slayerdramon"], "tribe": "blazing", "skills": [["blazing", 1]], "v2": 0},
	"wisemon": {"name": "Wisemon", "evol": "ultimate", "next": ["venommyotismon", "piedmon", "belphemon-sm"], "tribe": "abyss", "skills": [["mirage", 1]], "v2": 0},
	"wizardmon": {"name": "Wizardmon", "evol": "champion", "next": ["skullmeramon", "myotismon", "wisemon"], "tribe": "abyss", "skills": [["electric", 1]], "v2": 0},
	"woodmon": {"name": "Woodmon", "evol": "champion", "next": ["cherrymon", "pumpkinmon", "taomon"], "tribe": "earth", "skills": [["earth", 1]], "v2": 0},
	"wormmon": {"name": "Wormmon", "evol": "rookie", "next": ["waspmon", "kabuterimon", "kuwagamon", "stingmon", "icedevimon"], "tribe": "earth", "skills": [["mirage", 1]], "v2": 0},
	"yokomon": {"name": "Yokomon", "evol": "in-training-ii", "next": ["elecmon", "biyomon", "wormmon"], "tribe": "mirage", "skills": [["mirage", 1]], "v2": 0},
	"zubaeagermon": {"name": "ZubaEagermon", "evol": "champion", "next": ["duramon"], "tribe": "mirage", "skills": [["mirage", 1]], "v2": 0},
	"zubamon": {"name": "Zubamon", "evol": "rookie", "next": ["zubaeagermon"], "tribe": "mirage", "skills": [["mirage", 1]], "v2": 0},
	"zudomon": {"name": "Zudomon", "evol": "ultimate", "next": ["metalgarurumon", "marineangemon", "vikemon"], "tribe": "glacier", "skills": [["electric", 1]], "v2": 0}
};
