var digi = {
	"aeroveedramon": {"evol": "ultimate", "dvol": ["ravemon", "dynasmon", "ulforceveedramon"], "tribe": "mirage", "dnas": 1}, 
	"agumon": {"evol": "rookie", "dvol": ["geogreymon", "greymon", "meramon", "tyrannomon", "sukamon"], "tribe": "blazing", "dnas": 1}, 
	"agumon-black": {"evol": "rookie", "dvol": ["growlmon", "cyclonemon", "tankmon", "tyrannomon", "greymon-blue"], "tribe": "blazing", "dnas": 1}, 
	"alphamon": {"evol": "mega", "dvol": [], "tribe": "bright", "dnas": 2}, 
	"ancientgreymon": {"evol": "mega", "dvol": [], "tribe": "blazing", "dnas": 1}, 
	"andromon": {"evol": "ultimate", "dvol": ["craniamon", "hiandromon", "tigervespamon"], "tribe": "electric", "dnas": 1}, 
	"angemon": {"evol": "champion", "dvol": ["garudamon", "magnaangemon", "shakkoumon", "kimeramon"], "tribe": "bright", "dnas": 1}, 
	"angewomon": {"evol": "ultimate", "dvol": ["magnadramon", "ophanimon", "mastemon"], "tribe": "bright", "dnas": 1}, 
	"ankylomon": {"evol": "champion", "dvol": ["magnaangemon", "meteormon", "shakkoumon", "skullgreymon"], "tribe": "earth", "dnas": 1}, 
	"antylamon": {"evol": "ultimate", "dvol": ["cherubimon-good", "dianamon", "diaboromon", "chaosgallantmon"], "tribe": "mirage", "dnas": 1}, 
	"aquilamon": {"evol": "champion", "dvol": ["aeroveedramon", "garudamon", "silphymon", "crowmon"], "tribe": "mirage", "dnas": 1}, 
	"armadillomon": {"evol": "rookie", "dvol": ["ankylomon", "cyclonemon", "goldnumemon", "tankmon", "geremon"], "tribe": "earth", "dnas": 1}, 
	"arresterdramon": {"evol": "mega", "dvol": [], "tribe": "blazing", "dnas": 1}, 
	"bakemon": {"evol": "champion", "dvol": ["bluemeramon", "pumpkinmon", "myotismon", "ladydevimon"], "tribe": "abyss", "dnas": 1}, 
	"bancholeomon": {"evol": "mega", "dvol": [], "tribe": "earth", "dnas": 1}, 
	"barbamon": {"evol": "mega", "dvol": [], "tribe": "abyss", "dnas": 1}, 
	"beelzemon": {"evol": "mega", "dvol": [], "tribe": "abyss", "dnas": 1}, 
	"belphemon-rm": {"evol": "mega", "dvol": ["belphemon-sm"], "tribe": "abyss", "dnas": 1}, 
	"belphemon-sm": {"evol": "mega", "dvol": ["belphemon-rm"], "tribe": "abyss", "dnas": 1}, 
	"betamon": {"evol": "rookie", "dvol": ["gekomon", "numemon", "seadramon", "shellnumemon", "vegiemon"], "tribe": "glacier", "dnas": 1}, 
	"birdramon": {"evol": "champion", "dvol": ["aeroveedramon", "garudamon", "chirinmon", "crowmon"], "tribe": "blazing", "dnas": 1}, 
	"biyomon": {"evol": "rookie", "dvol": ["kabuterimon", "aquilamon", "birdramon", "kyubimon"], "tribe": "mirage", "dnas": 1}, 
	"blackgatomon": {"evol": "champion", "dvol": ["cyberdramon", "knightmon", "ladydevimon", "weregarurumon-black"], "tribe": "abyss", "dnas": 1}, 
	"blackkingnumemon": {"evol": "ultimate", "dvol": ["platinumnumemon", "metaletemon", "princemamemon"], "tribe": "abyss", "dnas": 1}, 
	"blackwargreymon": {"evol": "mega", "dvol": ["omegamon-zwart", "blackwargreymon-x"], "tribe": "blazing", "dnas": 2}, 
	"blackwargreymon-x": {"evol": "mega", "dvol": [], "tribe": "blazing", "dnas": 1}, 
	"bluemeramon": {"evol": "ultimate", "dvol": ["barbamon", "boltmon", "creepymon"], "tribe": "blazing", "dnas": 1}, 
	"boltmon": {"evol": "mega", "dvol": [], "tribe": "electric", "dnas": 1}, 
	"botamon": {"evol": "in-training-i", "dvol": ["koromon", "wanyamon"], "tribe": "mirage", "dnas": 1}, 
	"breakdramon": {"evol": "mega", "dvol": ["examon"], "tribe": "electric", "dnas": 1}, 
	"bukamon": {"evol": "in-training-ii", "dvol": ["otamamon", "gomamon", "syakomon", "betamon"], "tribe": "mirage", "dnas": 1}, 
	"cannonbeemon": {"evol": "ultimate", "dvol": ["megagargomon", "groundlocomon", "tigervespamon"], "tribe": "electric", "dnas": 1}, 
	"chaosdramon": {"evol": "mega", "dvol": [], "tribe": "electric", "dnas": 1}, 
	"chaosgallantmon": {"evol": "mega", "dvol": [], "tribe": "abyss", "dnas": 2}, 
	"cherrymon": {"evol": "ultimate", "dvol": ["grankuwagamon", "kuzuhamon", "puppetmon"], "tribe": "earth", "dnas": 1}, 
	"cherubimon-good": {"evol": "mega", "dvol": [], "tribe": "bright", "dnas": 1}, 
	"chirinmon": {"evol": "ultimate", "dvol": ["ophanimon", "seraphimon", "kentaurosmon"], "tribe": "bright", "dnas": 1}, 
	"chrysalimon": {"evol": "champion", "dvol": ["cyberdramon", "infermon", "taomon"], "tribe": "abyss", "dnas": 1}, 
	"clockmon": {"evol": "champion", "dvol": ["andromon", "knightmon", "datamon", "wisemon"], "tribe": "electric", "dnas": 1}, 
	"coredramon-blue": {"evol": "champion", "dvol": ["wingdramon"], "tribe": "blazing", "dnas": 1}, 
	"coredramon-green": {"evol": "champion", "dvol": ["groundramon"], "tribe": "earth", "dnas": 1}, 
	"craniamon": {"evol": "mega", "dvol": [], "tribe": "earth", "dnas": 2}, 
	"creepymon": {"evol": "mega", "dvol": [], "tribe": "abyss", "dnas": 1}, 
	"crowmon": {"evol": "ultimate", "dvol": ["minervamon", "ravemon", "kuzuhamon"], "tribe": "mirage", "dnas": 1}, 
	"cyberdramon": {"evol": "ultimate", "dvol": ["justimon", "titamon", "alphamon"], "tribe": "abyss", "dnas": 1}, 
	"cyclonemon": {"evol": "champion", "dvol": ["megadramon", "dorugreymon", "datamon"], "tribe": "earth", "dnas": 1}, 
	"datamon": {"evol": "ultimate", "dvol": ["machinedramon", "metalgarurumon-black", "groundlocomon"], "tribe": "electric", "dnas": 1}, 
	"demidevimon": {"evol": "rookie", "dvol": ["bakemon", "devimon", "kyubimon", "chrysalimon", "icedevimon"], "tribe": "abyss", "dnas": 1}, 
	"devimon": {"evol": "champion", "dvol": ["bluemeramon", "infermon", "metalgreymon-blue", "myotismon", "kimeramon"], "tribe": "abyss", "dnas": 1}, 
	"diaboromon": {"evol": "mega", "dvol": [], "tribe": "abyss", "dnas": 1}, 
	"dianamon": {"evol": "mega", "dvol": [], "tribe": "glacier", "dnas": 1}, 
	"digitamamon": {"evol": "ultimate", "dvol": ["minervamon", "belphemon-sm", "titamon"], "tribe": "mirage", "dnas": 1}, 
	"dorugamon": {"evol": "champion", "dvol": ["rizegreymon", "dorugreymon", "chirinmon"], "tribe": "mirage", "dnas": 1}, 
	"dorugreymon": {"evol": "ultimate", "dvol": ["alphamon", "kentaurosmon"], "tribe": "mirage", "dnas": 1}, 
	"dorumon": {"evol": "rookie", "dvol": ["cyclonemon", "dorugamon", "guardromon", "waspmon"], "tribe": "mirage", "dnas": 1}, 
	"dracomon": {"evol": "rookie", "dvol": ["coredramon-blue", "coredramon-green"], "tribe": "mirage", "dnas": 1}, 
	"duramon": {"evol": "ultimate", "dvol": ["durandamon"], "tribe": "mirage", "dnas": 1}, 
	"durandamon": {"evol": "mega", "dvol": [], "tribe": "mirage", "dnas": 1}, 
	"dynasmon": {"evol": "mega", "dvol": [], "tribe": "mirage", "dnas": 2}, 
	"ebemon": {"evol": "mega", "dvol": [], "tribe": "electric", "dnas": 1}, 
	"elecmon": {"evol": "rookie", "dvol": ["garurumon", "leomon", "nanimon", "sukamon", "garurumon-black", "geremon"], "tribe": "electric", "dnas": 1}, 
	"etemon": {"evol": "ultimate", "dvol": ["metaletemon", "piedmon", "platinumnumemon", "kingetemon"], "tribe": "abyss", "dnas": 1}, 
	"examon": {"evol": "mega", "dvol": [], "tribe": "blazing", "dnas": 2}, 
	"exveemon": {"evol": "champion", "dvol": ["magnaangemon", "paildramon", "rizegreymon"], "tribe": "mirage", "dnas": 1}, 
	"falcomon": {"evol": "rookie", "dvol": ["stingmon", "exveemon", "aquilamon", "peckmon"], "tribe": "mirage", "dnas": 1}, 
	"flamedramon": {"evol": "champion", "dvol": [], "tribe": "blazing", "dnas": 1}, 
	"frigimon": {"evol": "champion", "dvol": ["zudomon", "angewomon", "monzaemon"], "tribe": "glacier", "dnas": 1}, 
	"gabumon": {"evol": "rookie", "dvol": ["dorugamon", "garurumon", "numemon", "veedramon", "frigimon"], "tribe": "blazing", "dnas": 1}, 
	"gabumon-black": {"evol": "rookie", "dvol": ["garurumon-black", "vegiemon", "reppamon", "frigimon"], "tribe": "blazing", "dnas": 1}, 
	"gaiomon": {"evol": "mega", "dvol": ["susanoomon"], "tribe": "blazing", "dnas": 1}, 
	"gallantmon": {"evol": "mega", "dvol": ["gallantmon-cm", "gallantmon-x"], "tribe": "bright", "dnas": 2}, 
	"gallantmon-cm": {"evol": "mega", "dvol": [], "tribe": "blazing", "dnas": 1}, 
	"gallantmon-x": {"evol": "mega", "dvol": [], "tribe": "bright", "dnas": 1}, 
	"gankoomon": {"evol": "mega", "dvol": [], "tribe": "blazing", "dnas": 2}, 
	"gaogamon": {"evol": "champion", "dvol": ["grapleomon", "machgaogamon", "weregarurumon"], "tribe": "earth", "dnas": 1}, 
	"gaomon": {"evol": "rookie", "dvol": ["gargomon", "gaogamon", "leomon", "togemon", "ogremon"], "tribe": "blazing", "dnas": 1}, 
	"gargomon": {"evol": "champion", "dvol": ["wargrowlmon", "antylamon", "rapidmon"], "tribe": "electric", "dnas": 1}, 
	"garudamon": {"evol": "ultimate", "dvol": ["phoenixmon", "justimon", "ravemon"], "tribe": "blazing", "dnas": 1}, 
	"garurumon": {"evol": "champion", "dvol": ["dorugreymon", "iceleomon", "weregarurumon", "zudomon", "kimeramon"], "tribe": "blazing", "dnas": 1}, 
	"garurumon-black": {"evol": "champion", "dvol": ["weregarurumon-black", "bluemeramon", "machgaogamon"], "tribe": "blazing", "dnas": 1}, 
	"gatomon": {"evol": "champion", "dvol": ["angewomon", "lillymon", "silphymon"], "tribe": "bright", "dnas": 1}, 
	"gazimon": {"evol": "rookie", "dvol": ["dorugamon", "gaogamon", "leomon", "chrysalimon", "nanimon", "garurumon-black"], "tribe": "abyss", "dnas": 1}, 
	"gekomon": {"evol": "champion", "dvol": ["megaseadramon", "shogungekomon", "whamon"], "tribe": "glacier", "dnas": 1}, 
	"geogreymon": {"evol": "champion", "dvol": ["gigadramon", "rizegreymon", "skullgreymon"], "tribe": "blazing", "dnas": 1}, 
	"geremon": {"evol": "champion", "dvol": ["etemon", "superstarmon", "metalmamemon"], "tribe": "electric", "dnas": 1}, 
	"gigadramon": {"evol": "ultimate", "dvol": ["metalseadramon", "machinedramon", "groundlocomon"], "tribe": "electric", "dnas": 1}, 
	"goblimon": {"evol": "rookie", "dvol": ["gaogamon", "growlmon", "nanimon", "ogremon", "greymon-blue"], "tribe": "earth", "dnas": 1}, 
	"goldnumemon": {"evol": "champion", "dvol": ["vademon", "platinumnumemon", "blackkingnumemon"], "tribe": "bright", "dnas": 1}, 
	"gomamon": {"evol": "rookie", "dvol": ["ankylomon", "ikkakumon", "sorcermon", "frigimon"], "tribe": "glacier", "dnas": 1}, 
	"gotsumon": {"evol": "rookie", "dvol": ["ankylomon", "clockmon", "starmon", "tankmon"], "tribe": "mirage", "dnas": 1}, 
	"grankuwagamon": {"evol": "mega", "dvol": [], "tribe": "mirage", "dnas": 1}, 
	"grapleomon": {"evol": "ultimate", "dvol": ["bancholeomon", "leopardmon", "saberleomon"], "tribe": "electric", "dnas": 1}, 
	"greymon": {"evol": "champion", "dvol": ["metalgreymon", "metalgreymon-blue", "megadramon", "skullgreymon", "kimeramon"], "tribe": "blazing", "dnas": 1}, 
	"greymon-blue": {"evol": "champion", "dvol": ["metalgreymon-blue", "knightmon", "dorugreymon"], "tribe": "blazing", "dnas": 1}, 
	"groundlocomon": {"evol": "mega", "dvol": [], "tribe": "electric", "dnas": 2}, 
	"groundramon": {"evol": "ultimate", "dvol": ["breakdramon"], "tribe": "earth", "dnas": 1}, 
	"growlmon": {"evol": "champion", "dvol": ["gigadramon", "wargrowlmon", "metalgreymon", "metaltyrannomon"], "tribe": "blazing", "dnas": 1}, 
	"guardromon": {"evol": "champion", "dvol": ["andromon", "grapleomon", "metalmamemon", "datamon"], "tribe": "electric", "dnas": 1}, 
	"guilmon": {"evol": "rookie", "dvol": ["geogreymon", "growlmon", "meramon", "tyrannomon", "greymon-blue"], "tribe": "blazing", "dnas": 1}, 
	"gumdramon": {"evol": "rookie", "dvol": ["arresterdramon"], "tribe": "blazing", "dnas": 1}, 
	"hackmon": {"evol": "rookie", "dvol": ["jesmon", "greymon", "geogreymon", "platinumsukamon"], "tribe": "blazing", "dnas": 1}, 
	"hagurumon": {"evol": "rookie", "dvol": ["clockmon", "goldnumemon", "guardromon", "starmon", "platinumsukamon"], "tribe": "electric", "dnas": 1}, 
	"hawkmon": {"evol": "rookie", "dvol": ["meramon", "aquilamon", "birdramon", "peckmon"], "tribe": "mirage", "dnas": 1}, 
	"herculeskabuterimon": {"evol": "mega", "dvol": [], "tribe": "earth", "dnas": 1}, 
	"hiandromon": {"evol": "mega", "dvol": [], "tribe": "electric", "dnas": 1}, 
	"icedevimon": {"evol": "champion", "dvol": ["myotismon", "cherrymon", "ladydevimon"], "tribe": "glacier", "dnas": 1}, 
	"iceleomon": {"evol": "ultimate", "dvol": ["bancholeomon", "saberleomon", "miragegaogamon"], "tribe": "glacier", "dnas": 1}, 
	"ikkakumon": {"evol": "champion", "dvol": ["machgaogamon", "whamon", "zudomon"], "tribe": "glacier", "dnas": 1}, 
	"imperialdramon-dm": {"evol": "mega", "dvol": ["imperialdramon-fm"], "tribe": "blazing", "dnas": 1}, 
	"imperialdramon-fm": {"evol": "mega", "dvol": ["imperialdramon-pm"], "tribe": "mirage", "dnas": 1}, 
	"imperialdramon-pm": {"evol": "mega", "dvol": [], "tribe": "bright", "dnas": 1}, 
	"impmon": {"evol": "rookie", "dvol": ["bakemon", "ogremon", "sorcermon", "blackgatomon", "wizardmon", "icedevimon"], "tribe": "abyss", "dnas": 1}, 
	"infermon": {"evol": "ultimate", "dvol": ["beelzemon", "diaboromon", "venommyotismon"], "tribe": "abyss", "dnas": 1}, 
	"jesmon": {"evol": "mega", "dvol": [], "tribe": "mirage", "dnas": 2}, 
	"justimon": {"evol": "mega", "dvol": [], "tribe": "bright", "dnas": 1}, 
	"kabuterimon": {"evol": "champion", "dvol": ["megakabuterimon", "cherrymon", "lilamon", "kimeramon"], "tribe": "earth", "dnas": 1}, 
	"kentaurosmon": {"evol": "mega", "dvol": [], "tribe": "bright", "dnas": 2}, 
	"keramon": {"evol": "rookie", "dvol": ["bakemon", "wizardmon", "chrysalimon", "platinumsukamon"], "tribe": "abyss", "dnas": 1}, 
	"kimeramon": {"evol": "ultimate", "dvol": ["millenniummon"], "tribe": "mirage", "dnas": 1}, 
	"kingetemon": {"evol": "mega", "dvol": [], "tribe": "earth", "dnas": 1}, 
	"knightmon": {"evol": "ultimate", "dvol": ["craniamon", "leopardmon", "lordknightmon"], "tribe": "mirage", "dnas": 1}, 
	"koromon": {"evol": "in-training-ii", "dvol": ["agumon", "guilmon", "toyagumon", "hackmon", "dracomon", "shoutmon"], "tribe": "mirage", "dnas": 1}, 
	"kudamon": {"evol": "rookie", "dvol": ["angemon", "goldnumemon", "peckmon", "reppamon"], "tribe": "bright", "dnas": 1}, 
	"kuramon": {"evol": "in-training-i", "dvol": ["tsumemon", "pagumon"], "tribe": "mirage", "dnas": 1}, 
	"kuwagamon": {"evol": "champion", "dvol": ["cherrymon", "okuwamon", "cannonbeemon", "kimeramon"], "tribe": "mirage", "dnas": 1}, 
	"kuzuhamon": {"evol": "mega", "dvol": [], "tribe": "abyss", "dnas": 1}, 
	"kyubimon": {"evol": "champion", "dvol": ["ladydevimon", "monzaemon", "taomon"], "tribe": "blazing", "dnas": 1}, 
	"ladydevimon": {"evol": "ultimate", "dvol": ["lilithmon", "lotosmon", "mastemon"], "tribe": "abyss", "dnas": 1}, 
	"lalamon": {"evol": "rookie", "dvol": ["sunflowmon", "togemon", "vegiemon", "woodmon"], "tribe": "earth", "dnas": 1}, 
	"leomon": {"evol": "champion", "dvol": ["grapleomon", "metalgreymon", "meteormon", "iceleomon"], "tribe": "earth", "dnas": 1}, 
	"leopardmon": {"evol": "mega", "dvol": ["leopardmon-lm"], "tribe": "bright", "dnas": 2}, 
	"leopardmon-lm": {"evol": "mega", "dvol": [], "tribe": "earth", "dnas": 1}, 
	"leviamon": {"evol": "mega", "dvol": [], "tribe": "glacier", "dnas": 1}, 
	"lilamon": {"evol": "ultimate", "dvol": ["lilithmon", "lotosmon", "rosemon"], "tribe": "earth", "dnas": 1}, 
	"lilithmon": {"evol": "mega", "dvol": [], "tribe": "abyss", "dnas": 1}, 
	"lillymon": {"evol": "ultimate", "dvol": ["magnadramon", "lotosmon", "rosemon"], "tribe": "earth", "dnas": 1}, 
	"lopmon": {"evol": "rookie", "dvol": ["gargomon", "devimon", "blackgatomon", "wizardmon"], "tribe": "earth", "dnas": 1}, 
	"lordknightmon": {"evol": "mega", "dvol": [], "tribe": "abyss", "dnas": 2}, 
	"lotosmon": {"evol": "mega", "dvol": [], "tribe": "earth", "dnas": 1}, 
	"lucemon": {"evol": "rookie", "dvol": ["angemon", "devimon", "lucemon-fm"], "tribe": "bright", "dnas": 1}, 
	"lucemon-fm": {"evol": "ultimate", "dvol": ["lucemon-sm"], "tribe": "mirage", "dnas": 1}, 
	"lucemon-sm": {"evol": "mega", "dvol": [], "tribe": "abyss", "dnas": 1}, 
	"machgaogamon": {"evol": "ultimate", "dvol": ["bancholeomon", "miragegaogamon", "megagargomon"], "tribe": "earth", "dnas": 1}, 
	"machinedramon": {"evol": "mega", "dvol": ["millenniummon", "chaosdramon"], "tribe": "electric", "dnas": 1}, 
	"magnaangemon": {"evol": "ultimate", "dvol": ["shinegreymon", "lordknightmon", "seraphimon"], "tribe": "bright", "dnas": 1}, 
	"magnadramon": {"evol": "mega", "dvol": [], "tribe": "bright", "dnas": 1}, 
	"magnamon": {"evol": "mega", "dvol": ["magnamon-x"], "tribe": "mirage", "dnas": 2}, 
	"magnamon-x": {"evol": "mega", "dvol": [], "tribe": "mirage", "dnas": 1}, 
	"mamemon": {"evol": "ultimate", "dvol": ["puppetmon", "princemamemon", "wargreymon"], "tribe": "mirage", "dnas": 1}, 
	"marineangemon": {"evol": "mega", "dvol": [], "tribe": "glacier", "dnas": 1}, 
	"mastemon": {"evol": "mega", "dvol": [], "tribe": "mirage", "dnas": 1}, 
	"megadramon": {"evol": "ultimate", "dvol": ["blackwargreymon", "machinedramon", "ulforceveedramon"], "tribe": "electric", "dnas": 1}, 
	"megagargomon": {"evol": "mega", "dvol": [], "tribe": "electric", "dnas": 1}, 
	"megakabuterimon": {"evol": "ultimate", "dvol": ["grankuwagamon", "herculeskabuterimon", "magnadramon"], "tribe": "earth", "dnas": 1}, 
	"megaseadramon": {"evol": "ultimate", "dvol": ["leviamon", "metalseadramon", "plesiomon"], "tribe": "glacier", "dnas": 1}, 
	"meicoomon": {"evol": "champion", "dvol": ["meicrackmon-vm"], "tribe": "mirage", "dnas": 1}, 
	"meicrackmon-vm": {"evol": "ultimate", "dvol": ["raguelmon"], "tribe": "abyss", "dnas": 1}, 
	"meramon": {"evol": "champion", "dvol": ["bluemeramon", "skullmeramon", "mamemon", "iceleomon"], "tribe": "blazing", "dnas": 1}, 
	"metaletemon": {"evol": "mega", "dvol": [], "tribe": "earth", "dnas": 1}, 
	"metalgarurumon": {"evol": "mega", "dvol": ["omegamon", "metalgarurumon-x"], "tribe": "electric", "dnas": 2}, 
	"metalgarurumon-black": {"evol": "mega", "dvol": ["omegamon-zwart"], "tribe": "electric", "dnas": 2}, 
	"metalgarurumon-x": {"evol": "mega", "dvol": [], "tribe": "electric", "dnas": 1}, 
	"metalgreymon": {"evol": "ultimate", "dvol": ["rusttyranomon", "gaiomon", "wargreymon", "ancientgreymon"], "tribe": "blazing", "dnas": 1}, 
	"metalgreymon-blue": {"evol": "ultimate", "dvol": ["wargreymon", "gaiomon", "blackwargreymon"], "tribe": "blazing", "dnas": 1}, 
	"metalmamemon": {"evol": "ultimate", "dvol": ["ebemon", "hiandromon", "princemamemon"], "tribe": "electric", "dnas": 1}, 
	"metalseadramon": {"evol": "mega", "dvol": [], "tribe": "glacier", "dnas": 1}, 
	"metaltyrannomon": {"evol": "ultimate", "dvol": ["blackwargreymon", "gallantmon", "rusttyranomon"], "tribe": "electric", "dnas": 1}, 
	"meteormon": {"evol": "ultimate", "dvol": ["ebemon", "metaletemon", "dianamon", "metalgarurumon"], "tribe": "mirage", "dnas": 1}, 
	"millenniummon": {"evol": "mega", "dvol": [], "tribe": "mirage", "dnas": 1}, 
	"minervamon": {"evol": "mega", "dvol": [], "tribe": "mirage", "dnas": 1}, 
	"miragegaogamon": {"evol": "mega", "dvol": ["omegamon-zwart-d", "miragegaogamon-bm"], "tribe": "bright", "dnas": 1}, 
	"miragegaogamon-bm": {"evol": "mega", "dvol": [], "tribe": "bright", "dnas": 1}, 
	"monzaemon": {"evol": "ultimate", "dvol": ["minervamon", "sakuyamon", "saberleomon"], "tribe": "mirage", "dnas": 1}, 
	"motimon": {"evol": "in-training-ii", "dvol": ["gotsumon", "solarmon", "tentomon", "hagurumon"], "tribe": "mirage", "dnas": 1}, 
	"myotismon": {"evol": "ultimate", "dvol": ["barbamon", "piedmon", "venommyotismon"], "tribe": "abyss", "dnas": 1}, 
	"nanimon": {"evol": "champion", "dvol": ["digitamamon", "superstarmon", "meteormon"], "tribe": "mirage", "dnas": 1}, 
	"numemon": {"evol": "champion", "dvol": ["blackkingnumemon", "etemon", "monzaemon"], "tribe": "glacier", "dnas": 1}, 
	"nyaromon": {"evol": "in-training-ii", "dvol": ["armadillomon", "terriermon", "salamon"], "tribe": "mirage", "dnas": 1}, 
	"ogremon": {"evol": "champion", "dvol": ["skullmeramon", "digitamamon", "weregarurumon"], "tribe": "earth", "dnas": 1}, 
	"okuwamon": {"evol": "ultimate", "dvol": ["diaboromon", "grankuwagamon", "herculeskabuterimon"], "tribe": "mirage", "dnas": 1}, 
	"omega-shoutmon": {"evol": "mega", "dvol": [], "tribe": "electric", "dnas": 1}, 
	"omegamon": {"evol": "mega", "dvol": ["omegamon-x"], "tribe": "bright", "dnas": 2}, 
	"omegamon-alter-b": {"evol": "mega", "dvol": [], "tribe": "abyss", "dnas": 1}, 
	"omegamon-x": {"evol": "mega", "dvol": [], "tribe": "bright", "dnas": 1}, 
	"omegamon-zwart": {"evol": "mega", "dvol": [], "tribe": "abyss", "dnas": 2}, 
	"omegamon-zwart-d": {"evol": "mega", "dvol": ["omegamon-alter-b"], "tribe": "abyss", "dnas": 1}, 
	"ophanimon": {"evol": "mega", "dvol": [], "tribe": "bright", "dnas": 1}, 
	"otamamon": {"evol": "rookie", "dvol": ["gekomon", "numemon", "seadramon", "shellnumemon"], "tribe": "glacier", "dnas": 1}, 
	"pabumon": {"evol": "in-training-i", "dvol": ["tanemon", "yokomon", "motimon"], "tribe": "mirage", "dnas": 1}, 
	"pagumon": {"evol": "in-training-ii", "dvol": ["impmon", "gazimon", "lopmon"], "tribe": "mirage", "dnas": 1}, 
	"paildramon": {"evol": "ultimate", "dvol": ["imperialdramon-dm"], "tribe": "mirage", "dnas": 1}, 
	"palmon": {"evol": "rookie", "dvol": ["kuwagamon", "togemon", "vegiemon", "sunflowmon", "woodmon"], "tribe": "earth", "dnas": 1}, 
	"patamon": {"evol": "rookie", "dvol": ["angemon", "birdramon", "reppamon", "gatomon", "exveemon"], "tribe": "bright", "dnas": 1}, 
	"peckmon": {"evol": "champion", "dvol": ["antylamon", "piximon", "crowmon"], "tribe": "mirage", "dnas": 1}, 
	"phoenixmon": {"evol": "mega", "dvol": [], "tribe": "blazing", "dnas": 1}, 
	"piedmon": {"evol": "mega", "dvol": [], "tribe": "abyss", "dnas": 1}, 
	"piximon": {"evol": "ultimate", "dvol": ["cherubimon-good", "marineangemon", "ophanimon"], "tribe": "bright", "dnas": 1}, 
	"platinumnumemon": {"evol": "mega", "dvol": [], "tribe": "mirage", "dnas": 1}, 
	"platinumsukamon": {"evol": "champion", "dvol": ["etemon", "metalmamemon", "vademon"], "tribe": "mirage", "dnas": 1}, 
	"plesiomon": {"evol": "mega", "dvol": [], "tribe": "glacier", "dnas": 1}, 
	"poyomon": {"evol": "in-training-i", "dvol": ["tokomon", "bukamon"], "tribe": "mirage", "dnas": 1}, 
	"princemamemon": {"evol": "mega", "dvol": [], "tribe": "mirage", "dnas": 1}, 
	"pumpkinmon": {"evol": "ultimate", "dvol": ["boltmon", "puppetmon", "rosemon"], "tribe": "earth", "dnas": 1}, 
	"punimon": {"evol": "in-training-i", "dvol": ["tsunomon", "nyaromon"], "tribe": "mirage", "dnas": 1}, 
	"puppetmon": {"evol": "mega", "dvol": [], "tribe": "earth", "dnas": 1}, 
	"raguelmon": {"evol": "mega", "dvol": [], "tribe": "abyss", "dnas": 1}, 
	"rapidmon": {"evol": "ultimate", "dvol": ["megagargomon", "tigervespamon", "metalgarurumon-black"], "tribe": "electric", "dnas": 1}, 
	"rapidmon-gold": {"evol": "champion", "dvol": [], "tribe": "bright", "dnas": 1}, 
	"ravemon": {"evol": "mega", "dvol": ["ravemon-bm"], "tribe": "electric", "dnas": 1}, 
	"ravemon-bm": {"evol": "mega", "dvol": [], "tribe": "electric", "dnas": 1}, 
	"renamon": {"evol": "rookie", "dvol": ["blackgatomon", "garurumon", "kyubimon", "woodmon"], "tribe": "bright", "dnas": 1}, 
	"reppamon": {"evol": "champion", "dvol": ["rapidmon", "piximon", "chirinmon"], "tribe": "bright", "dnas": 1}, 
	"rizegreymon": {"evol": "ultimate", "dvol": ["gaiomon", "shinegreymon"], "tribe": "blazing", "dnas": 1}, 
	"rosemon": {"evol": "mega", "dvol": ["rosemon-bm"], "tribe": "earth", "dnas": 1}, 
	"rosemon-bm": {"evol": "mega", "dvol": [], "tribe": "earth", "dnas": 1}, 
	"rusttyranomon": {"evol": "mega", "dvol": [], "tribe": "electric", "dnas": 1}, 
	"saberleomon": {"evol": "mega", "dvol": [], "tribe": "earth", "dnas": 1}, 
	"sakuyamon": {"evol": "mega", "dvol": [], "tribe": "bright", "dnas": 1}, 
	"salamon": {"evol": "rookie", "dvol": ["frigimon", "reppamon", "gatomon", "veedramon", "sorcermon"], "tribe": "bright", "dnas": 1}, 
	"seadramon": {"evol": "champion", "dvol": ["shogungekomon", "megaseadramon", "whamon"], "tribe": "glacier", "dnas": 1}, 
	"seraphimon": {"evol": "mega", "dvol": [], "tribe": "bright", "dnas": 1}, 
	"shakkoumon": {"evol": "ultimate", "dvol": ["cherubimon-good", "vikemon", "seraphimon"], "tribe": "bright", "dnas": 1}, 
	"shellnumemon": {"evol": "champion", "dvol": ["blackkingnumemon", "megaseadramon", "shogungekomon"], "tribe": "glacier", "dnas": 1}, 
	"shinegreymon": {"evol": "mega", "dvol": ["omegamon-zwart-d", "shinegreymon-bm", "shinegreymon-rm"], "tribe": "bright", "dnas": 1}, 
	"shinegreymon-bm": {"evol": "mega", "dvol": [], "tribe": "blazing", "dnas": 1}, 
	"shinegreymon-rm": {"evol": "mega", "dvol": [], "tribe": "abyss", "dnas": 1}, 
	"shogungekomon": {"evol": "ultimate", "dvol": ["plesiomon", "leviamon", "vikemon"], "tribe": "glacier", "dnas": 1}, 
	"shoutmon": {"evol": "rookie", "dvol": ["omega-shoutmon"], "tribe": "electric", "dnas": 1}, 
	"silphymon": {"evol": "ultimate", "dvol": ["dynasmon", "phoenixmon", "sakuyamon"], "tribe": "electric", "dnas": 1}, 
	"skullgreymon": {"evol": "ultimate", "dvol": ["creepymon", "shinegreymon", "titamon"], "tribe": "abyss", "dnas": 1}, 
	"skullmeramon": {"evol": "ultimate", "dvol": ["gankoomon", "beelzemon", "boltmon"], "tribe": "blazing", "dnas": 1}, 
	"slayerdramon": {"evol": "mega", "dvol": ["examon"], "tribe": "blazing", "dnas": 1}, 
	"solarmon": {"evol": "rookie", "dvol": ["clockmon", "geremon", "starmon", "meramon"], "tribe": "bright", "dnas": 1}, 
	"sorcermon": {"evol": "champion", "dvol": ["antylamon", "piximon", "wisemon"], "tribe": "glacier", "dnas": 1}, 
	"starmon": {"evol": "champion", "dvol": ["mamemon", "metalmamemon", "superstarmon"], "tribe": "bright", "dnas": 1}, 
	"stingmon": {"evol": "champion", "dvol": ["infermon", "paildramon", "okuwamon"], "tribe": "earth", "dnas": 1}, 
	"sukamon": {"evol": "champion", "dvol": ["superstarmon", "etemon", "vademon"], "tribe": "mirage", "dnas": 1}, 
	"sunflowmon": {"evol": "champion", "dvol": ["angewomon", "lilamon", "lillymon"], "tribe": "earth", "dnas": 1}, 
	"superstarmon": {"evol": "ultimate", "dvol": ["justimon", "gankoomon", "platinumnumemon"], "tribe": "bright", "dnas": 1}, 
	"susanoomon": {"evol": "mega", "dvol": [], "tribe": "bright", "dnas": 1}, 
	"syakomon": {"evol": "rookie", "dvol": ["ikkakumon", "shellnumemon", "gekomon", "seadramon"], "tribe": "glacier", "dnas": 1}, 
	"tanemon": {"evol": "in-training-ii", "dvol": ["palmon", "lalamon", "renamon"], "tribe": "mirage", "dnas": 1}, 
	"tankmon": {"evol": "champion", "dvol": ["andromon", "gigadramon", "cannonbeemon", "knightmon"], "tribe": "electric", "dnas": 1}, 
	"taomon": {"evol": "ultimate", "dvol": ["dianamon", "kuzuhamon", "sakuyamon", "phoenixmon"], "tribe": "abyss", "dnas": 1}, 
	"tentomon": {"evol": "rookie", "dvol": ["kabuterimon", "waspmon", "kuwagamon", "stingmon", "sunflowmon"], "tribe": "electric", "dnas": 1}, 
	"terriermon": {"evol": "rookie", "dvol": ["gargomon", "ikkakumon", "gatomon", "rapidmon-gold"], "tribe": "earth", "dnas": 1}, 
	"tigervespamon": {"evol": "mega", "dvol": [], "tribe": "electric", "dnas": 1}, 
	"titamon": {"evol": "mega", "dvol": [], "tribe": "earth", "dnas": 1}, 
	"togemon": {"evol": "champion", "dvol": ["machgaogamon", "lillymon", "pumpkinmon"], "tribe": "earth", "dnas": 1}, 
	"tokomon": {"evol": "in-training-ii", "dvol": ["patamon", "falcomon", "hawkmon", "lucemon"], "tribe": "mirage", "dnas": 1}, 
	"toyagumon": {"evol": "rookie", "dvol": ["clockmon", "greymon", "guardromon", "sukamon", "starmon"], "tribe": "electric", "dnas": 1}, 
	"tsumemon": {"evol": "in-training-ii", "dvol": ["agumon-black", "keramon", "demidevimon"], "tribe": "mirage", "dnas": 1}, 
	"tsunomon": {"evol": "in-training-ii", "dvol": ["gabumon", "gabumon-black", "goblimon", "veemon", "gumdramon", "zubamon"], "tribe": "mirage", "dnas": 1}, 
	"tyrannomon": {"evol": "champion", "dvol": ["mamemon", "megadramon", "metalgreymon-blue", "metaltyrannomon"], "tribe": "blazing", "dnas": 1}, 
	"ulforceveedramon": {"evol": "mega", "dvol": [], "tribe": "bright", "dnas": 2}, 
	"vademon": {"evol": "ultimate", "dvol": ["ebemon", "herculeskabuterimon", "hiandromon"], "tribe": "abyss", "dnas": 1}, 
	"veedramon": {"evol": "champion", "dvol": ["aeroveedramon", "cyberdramon", "metaltyrannomon", "wargrowlmon"], "tribe": "mirage", "dnas": 1}, 
	"veemon": {"evol": "rookie", "dvol": ["flamedramon", "magnamon", "veedramon", "exveemon"], "tribe": "mirage", "dnas": 1}, 
	"vegiemon": {"evol": "champion", "dvol": ["digitamamon", "lilamon", "megakabuterimon"], "tribe": "earth", "dnas": 1}, 
	"venommyotismon": {"evol": "mega", "dvol": [], "tribe": "abyss", "dnas": 1}, 
	"vikemon": {"evol": "mega", "dvol": [], "tribe": "glacier", "dnas": 1}, 
	"volcanicdramon": {"evol": "mega", "dvol": [], "tribe": "blazing", "dnas": 1}, 
	"wanyamon": {"evol": "in-training-ii", "dvol": ["gaomon", "kudamon", "dorumon"], "tribe": "mirage", "dnas": 1}, 
	"wargreymon": {"evol": "mega", "dvol": ["omegamon", "wargreymon-x"], "tribe": "blazing", "dnas": 2}, 
	"wargreymon-x": {"evol": "mega", "dvol": [], "tribe": "blazing", "dnas": 1}, 
	"wargrowlmon": {"evol": "ultimate", "dvol": ["gallantmon", "chaosgallantmon", "rusttyranomon"], "tribe": "blazing", "dnas": 1}, 
	"waspmon": {"evol": "champion", "dvol": ["cannonbeemon", "rapidmon", "megakabuterimon", "okuwamon"], "tribe": "electric", "dnas": 1}, 
	"weregarurumon": {"evol": "ultimate", "dvol": ["metalgarurumon", "metalgarurumon-black", "miragegaogamon"], "tribe": "earth", "dnas": 1}, 
	"weregarurumon-black": {"evol": "ultimate", "dvol": ["metalgarurumon-black", "minervamon", "bancholeomon"], "tribe": "earth", "dnas": 1}, 
	"whamon": {"evol": "ultimate", "dvol": ["plesiomon", "marineangemon", "metalseadramon"], "tribe": "glacier", "dnas": 1}, 
	"wingdramon": {"evol": "ultimate", "dvol": ["slayerdramon"], "tribe": "blazing", "dnas": 1}, 
	"wisemon": {"evol": "ultimate", "dvol": ["venommyotismon", "piedmon", "belphemon-sm"], "tribe": "abyss", "dnas": 1}, 
	"wizardmon": {"evol": "champion", "dvol": ["skullmeramon", "myotismon", "wisemon"], "tribe": "abyss", "dnas": 1}, 
	"woodmon": {"evol": "champion", "dvol": ["cherrymon", "pumpkinmon", "taomon"], "tribe": "earth", "dnas": 1}, 
	"wormmon": {"evol": "rookie", "dvol": ["waspmon", "kabuterimon", "kuwagamon", "stingmon", "icedevimon"], "tribe": "earth", "dnas": 1}, 
	"yokomon": {"evol": "in-training-ii", "dvol": ["elecmon", "biyomon", "wormmon"], "tribe": "mirage", "dnas": 1}, 
	"zubaeagermon": {"evol": "champion", "dvol": ["duramon"], "tribe": "mirage", "dnas": 1}, 
	"zubamon": {"evol": "rookie", "dvol": ["zubaeagermon"], "tribe": "mirage", "dnas": 1}, 
	"zudomon": {"evol": "ultimate", "dvol": ["metalgarurumon", "marineangemon", "vikemon"], "tribe": "glacier", "dnas": 1}
};
