// /* run this on http://growlmon.net/digivolvetree */
// var digi = {};
// var mons = Array.from(document.getElementsByClassName("blockListEl")).map(function (blockListEl) {
//     return blockListEl.getElementsByTagName("a")[0].href.split("/")[4];
// });
// mons.forEach(function (mon) {
//     var xhr = new XMLHttpRequest();
//     xhr.open("GET", "http://growlmon.net/digimon/" + mon, true);
//     xhr.onload = function () {
//         var content = document.createElement("div");
//         content.innerHTML = this.response;
//         digi[mon] = Array.from(
//             content.getElementsByClassName("dvolveTable")[0].rows[0].cells[2].getElementsByTagName("a")
//         ).map(function (a) {
//             return a.href.split("/")[4];
//         });
//     };
//     xhr.send();
// });

/* run independently from above */
var digi = {
    "aeroveedramon": ["ravemon","dynasmon","ulforceveedramon"],
    "agumon-mutant": ["geogreymon-mutant","greymon-mutant"],
    "agumon-black": ["growlmon","cyclonemon","tankmon","tyrannomon","greymon-blue"],
    "alphamon": [],
    "agumon": ["geogreymon","greymon","meramon","tyrannomon","sukamon"],
    "ancientgreymon": [],
    "andromon": ["craniamon","hiandromon","tigervespamon"],
    "angemon": ["garudamon","magnaangemon","shakkoumon","kimeramon"],
    "angewomon": ["magnadramon","ophanimon","mastemon"],
    "antylamon": ["cherubimon-good","dianamon","diaboromon","chaosgallantmon"],
    "ankylomon": ["magnaangemon","meteormon","shakkoumon","skullgreymon"],
    "antylamon-mutant": ["dianamon-mutant"],
    "aquilamon": ["aeroveedramon","garudamon","silphymon","crowmon"],
    "armadillomon": ["ankylomon","cyclonemon","goldnumemon","tankmon","geremon"],
    "arresterdramon": [],
    "bakemon": ["bluemeramon","pumpkinmon","myotismon","ladydevimon"],
    "bancholeomon": [],
    "barbamon": [],
    "beelzemon": [],
    "belphemon-rm": [],
    "belphemon-sm": ["belphemon-rm"],
    "betamon": ["gekomon","numemon","seadramon","shellnumemon","vegiemon"],
    "birdramon": ["aeroveedramon","garudamon","chirinmon","crowmon"],
    "biyomon": ["kabuterimon","aquilamon","birdramon","kyubimon"],
    "blackgatomon": ["cyberdramon","knightmon","ladydevimon","weregarurumon-black"],
    "blackkingnumemon": ["platinumnumemon","metaletemon","princemamemon"],
    "blackwargreymon": ["omegamon-zwart","blackwargreymon-x"],
    "blackwargreymon-x": [],
    "bluemeramon": ["barbamon","boltmon","creepymon"],
    "boltmon": [],
    "botamon": ["koromon","wanyamon"],
    "botamon-mutant": ["koromon-mutant"],
    "breakdramon": ["examon"],
    "bukamon": ["otamamon","gomamon","syakomon","betamon"],
    "bukamon-mutant": ["gomamon-mutant","otamamon-mutant"],
    "cannonbeemon": ["megagargomon","groundlocomon","tigervespamon"],
    "chaosdramon": [],
    "chaosgallantmon": [],
    "cherrymon": ["grankuwagamon","kuzuhamon","puppetmon"],
    "cherubimon-good": [],
    "chirinmon": ["ophanimon","seraphimon","kentaurosmon"],
    "chrysalimon": ["cyberdramon","infermon","taomon"],
    "clockmon": ["andromon","knightmon","datamon","wisemon"],
    "coredramon-blue": ["wingdramon"],
    "coredramon-green": ["groundramon"],
    "craniamon": [],
    "creepymon": [],
    "crowmon": ["minervamon","ravemon","kuzuhamon"],
    "cyberdramon": ["justimon","titamon","alphamon"],
    "cyclonemon": ["megadramon","dorugreymon","datamon"],
    "datamon": ["machinedramon","metalgarurumon-black","groundlocomon"],
    "demidevimon": ["bakemon","devimon","kyubimon","chrysalimon","icedevimon"],
    "devimon": ["bluemeramon","infermon","metalgreymon-blue","myotismon","kimeramon"],
    "diaboromon": [],
    "dianamon": [],
    "dianamon-mutant": [],
    "digitamamon": ["minervamon","belphemon-sm","titamon"],
    "dorugamon": ["rizegreymon","dorugreymon","chirinmon"],
    "dorugreymon": ["alphamon","kentaurosmon"],
    "dorumon": ["cyclonemon","dorugamon","guardromon","waspmon"],
    "dracomon": ["coredramon-blue","coredramon-green"],
    "duramon": ["durandamon"],
    "durandamon": [],
    "dynasmon": [],
    "ebemon": [],
    "etemon": ["metaletemon","piedmon","platinumnumemon","kingetemon"],
    "elecmon": ["garurumon","leomon","nanimon","sukamon","garurumon-black","geremon"],
    "examon": [],
    "exveemon": ["magnaangemon","paildramon","rizegreymon"],
    "falcomon": ["stingmon","exveemon","aquilamon","peckmon"],
    "flamedramon": [],
    "frigimon": ["zudomon","angewomon","monzaemon"],
    "gabumon": ["dorugamon","garurumon","numemon","veedramon","frigimon"],
    "gabumon-black": ["garurumon-black","vegiemon","reppamon","frigimon"],
    "gaiomon": ["susanoomon"],
    "gaiomon-mutant": [],
    "gallantmon": ["gallantmon-cm","gallantmon-x"],
    "gallantmon-cm": [],
    "gallantmon-x": [],
    "gankoomon": [],
    "gaogamon": ["grapleomon","machgaogamon","weregarurumon"],
    "gaomon": ["gargomon","gaogamon","leomon","togemon","ogremon"],
    "gargomon": ["wargrowlmon","antylamon","rapidmon"],
    "gargomon-mutant": ["antylamon-mutant"],
    "garudamon": ["phoenixmon","justimon","ravemon"],
    "garurumon": ["dorugreymon","iceleomon","weregarurumon","zudomon","kimeramon"],
    "garurumon-black": ["weregarurumon-black","bluemeramon","machgaogamon"],
    "gatomon": ["angewomon","lillymon","silphymon"],
    "gazimon": ["dorugamon","gaogamon","leomon","chrysalimon","nanimon","garurumon-black"],
    "gekomon": ["megaseadramon","shogungekomon","whamon"],
    "geogreymon": ["gigadramon","rizegreymon","skullgreymon"],
    "geogreymon-mutant": ["rizegreymon-mutant"],
    "geremon": ["etemon","superstarmon","metalmamemon"],
    "gigadramon": ["metalseadramon","machinedramon","groundlocomon"],
    "goblimon": ["gaogamon","growlmon","nanimon","ogremon","greymon-blue"],
    "goldnumemon": ["vademon","platinumnumemon","blackkingnumemon"],
    "gomamon": ["ankylomon","ikkakumon","sorcermon","frigimon"],
    "gomamon-mutant": ["ikkakumon-mutant"],
    "gotsumon": ["ankylomon","clockmon","starmon","tankmon"],
    "grankuwagamon": [],
    "grapleomon": ["bancholeomon","leopardmon","saberleomon"],
    "greymon": ["metalgreymon","metalgreymon-blue","megadramon","skullgreymon","kimeramon"],
    "greymon-blue": ["metalgreymon-blue","knightmon","dorugreymon"],
    "greymon-mutant": ["metalgreymon-mutant"],
    "groundlocomon": [],
    "groundramon": ["breakdramon"],
    "growlmon": ["gigadramon","wargrowlmon","metalgreymon","metaltyrannomon"],
    "guardromon": ["andromon","grapleomon","metalmamemon","datamon"],
    "guilmon": ["geogreymon","growlmon","meramon","tyrannomon","greymon-blue"],
    "gumdramon": ["arresterdramon"],
    "herculeskabuterimon": [],
    "herculeskabuterimon-mutant": [],
    "hawkmon": ["meramon","aquilamon","birdramon","peckmon"],
    "hagurumon": ["clockmon","goldnumemon","guardromon","starmon","platinumsukamon"],
    "hackmon": ["jesmon","greymon","geogreymon","platinumsukamon"],
    "hiandromon": [],
    "icedevimon": ["myotismon","cherrymon","ladydevimon"],
    "iceleomon": ["bancholeomon","saberleomon","miragegaogamon"],
    "ikkakumon": ["machgaogamon","whamon","zudomon"],
    "ikkakumon-mutant": ["whamon-mutant"],
    "imperialdramon-dm": ["imperialdramon-fm"],
    "imperialdramon-fm": ["imperialdramon-pm"],
    "imperialdramon-pm": [],
    "impmon": ["bakemon","ogremon","sorcermon","blackgatomon","wizardmon","icedevimon"],
    "infermon": ["beelzemon","diaboromon","venommyotismon"],
    "jesmon": [],
    "justimon": [],
    "kabuterimon": ["megakabuterimon","cherrymon","lilamon","kimeramon"],
    "kabuterimon-mutant": ["megakabuterimon-mutant"],
    "kentaurosmon": [],
    "keramon": ["bakemon","wizardmon","chrysalimon","platinumsukamon"],
    "kimeramon": ["millenniummon"],
    "kingetemon": [],
    "knightmon": ["craniamon","leopardmon","lordknightmon"],
    "koromon": ["agumon","guilmon","toyagumon","hackmon","dracomon","shoutmon"],
    "kuramon": ["tsumemon","pagumon"],
    "koromon-mutant": ["agumon-mutant"],
    "kudamon": ["angemon","goldnumemon","peckmon","reppamon"],
    "kuwagamon": ["cherrymon","okuwamon","cannonbeemon","kimeramon"],
    "kuzuhamon": [],
    "kyubimon": ["ladydevimon","monzaemon","taomon"],
    "kyubimon-mutant": ["taomon-mutant"],
    "ladydevimon": ["lilithmon","lotosmon","mastemon"],
    "lalamon": ["sunflowmon","togemon","vegiemon","woodmon"],
    "leomon": ["grapleomon","metalgreymon","meteormon","iceleomon"],
    "leopardmon": ["leopardmon-lm"],
    "leopardmon-lm": [],
    "leviamon": [],
    "leviamon-mutant": [],
    "lilamon": ["lilithmon","lotosmon","rosemon"],
    "lilithmon": [],
    "lillymon": ["magnadramon","lotosmon","rosemon"],
    "lopmon": ["gargomon","devimon","blackgatomon","wizardmon"],
    "lordknightmon": [],
    "lotosmon": [],
    "lucemon": ["angemon","devimon","lucemon-fm"],
    "lucemon-fm": ["lucemon-sm"],
    "lucemon-sm": [],
    "machgaogamon": ["bancholeomon","miragegaogamon","megagargomon"],
    "machinedramon": ["millenniummon","chaosdramon"],
    "magnaangemon": ["shinegreymon","lordknightmon","seraphimon"],
    "magnadramon": [],
    "magnamon": ["magnamon-x"],
    "magnamon-x": [],
    "mamemon": ["puppetmon","princemamemon","wargreymon"],
    "marineangemon": [],
    "mastemon": [],
    "megadramon": ["blackwargreymon","machinedramon","ulforceveedramon"],
    "megagargomon": [],
    "megakabuterimon": ["grankuwagamon","herculeskabuterimon","magnadramon"],
    "megakabuterimon-mutant": ["herculeskabuterimon-mutant"],
    "megaseadramon": ["leviamon","metalseadramon","plesiomon"],
    "megaseadramon-mutant": ["leviamon-mutant"],
    "meicoomon": ["meicrackmon-vm"],
    "meicrackmon-vm": ["raguelmon"],
    "meramon": ["bluemeramon","skullmeramon","mamemon","iceleomon"],
    "metaletemon": [],
    "metalgarurumon": ["omegamon","metalgarurumon-x"],
    "metalgarurumon-black": ["omegamon-zwart"],
    "metalgarurumon-x": [],
    "metalgreymon": ["rusttyranomon","gaiomon","wargreymon","ancientgreymon"],
    "metalgreymon-blue": ["wargreymon","gaiomon","blackwargreymon"],
    "metalgreymon-mutant": ["gaiomon-mutant"],
    "metalmamemon": ["ebemon","hiandromon","princemamemon"],
    "metalseadramon": [],
    "metaltyrannomon": ["blackwargreymon","gallantmon","rusttyranomon"],
    "meteormon": ["ebemon","metaletemon","dianamon","metalgarurumon"],
    "millenniummon": [],
    "minervamon": [],
    "miragegaogamon": ["omegamon-zwart-d","miragegaogamon-bm"],
    "miragegaogamon-bm": [],
    "monzaemon": ["minervamon","sakuyamon","saberleomon"],
    "motimon": ["gotsumon","solarmon","tentomon","hagurumon"],
    "motimon-mutant": ["tentomon-mutant"],
    "myotismon": ["barbamon","piedmon","venommyotismon"],
    "nanimon": ["digitamamon","superstarmon","meteormon"],
    "numemon": ["blackkingnumemon","etemon","monzaemon"],
    "nyaromon": ["armadillomon","terriermon","salamon"],
    "nyaromon-mutant": ["terriermon-mutant"],
    "ogremon": ["skullmeramon","digitamamon","weregarurumon"],
    "okuwamon": ["diaboromon","grankuwagamon","herculeskabuterimon"],
    "omega-shoutmon": [],
    "omegamon": ["omegamon-x"],
    "omegamon-alter-b": [],
    "omegamon-x": [],
    "omegamon-zwart": [],
    "omegamon-zwart-d": ["omegamon-alter-b"],
    "ophanimon": [],
    "otamamon": ["gekomon","numemon","seadramon","shellnumemon"],
    "otamamon-mutant": ["seadramon-mutant"],
    "pabumon": ["tanemon","yokomon","motimon"],
    "pabumon-mutant": ["motimon-mutant","tanemon-mutant"],
    "pagumon": ["impmon","gazimon","lopmon"],
    "paildramon": ["imperialdramon-dm"],
    "palmon": ["kuwagamon","togemon","vegiemon","sunflowmon","woodmon"],
    "patamon": ["angemon","birdramon","reppamon","gatomon","exveemon"],
    "peckmon": ["antylamon","piximon","crowmon"],
    "phoenixmon": [],
    "piedmon": [],
    "piximon": ["cherubimon-good","marineangemon","ophanimon"],
    "platinumnumemon": [],
    "platinumsukamon": ["etemon","metalmamemon","vademon"],
    "plesiomon": [],
    "plesiomon-mutant": [],
    "poyomon": ["tokomon","bukamon"],
    "poyomon-mutant": ["bukamon-mutant"],
    "princemamemon": [],
    "pumpkinmon": ["boltmon","puppetmon","rosemon"],
    "punimon": ["tsunomon","nyaromon"],
    "punimon-mutant": ["nyaromon-mutant"],
    "puppetmon": [],
    "raguelmon": [],
    "rapidmon": ["megagargomon","tigervespamon","metalgarurumon-black"],
    "rapidmon-gold": [],
    "ravemon": ["ravemon-bm"],
    "ravemon-bm": [],
    "renamon-mutant": ["kyubimon-mutant"],
    "reppamon": ["rapidmon","piximon","chirinmon"],
    "rizegreymon": ["gaiomon","shinegreymon"],
    "rosemon": ["rosemon-bm"],
    "renamon": ["blackgatomon","garurumon","kyubimon","woodmon"],
    "rosemon-bm": [],
    "rusttyranomon": [],
    "saberleomon": [],
    "rizegreymon-mutant": ["shinegreymon-mutant"],
    "sakuyamon-mutant": [],
    "sakuyamon": [],
    "salamon": ["frigimon","reppamon","gatomon","veedramon","sorcermon"],
    "seadramon": ["shogungekomon","megaseadramon","whamon"],
    "seadramon-mutant": ["megaseadramon-mutant"],
    "seraphimon": [],
    "shakkoumon": ["cherubimon-good","vikemon","seraphimon"],
    "shellnumemon": ["blackkingnumemon","megaseadramon","shogungekomon"],
    "shinegreymon": ["omegamon-zwart-d","shinegreymon-bm","shinegreymon-rm"],
    "shinegreymon-mutant": [],
    "shinegreymon-rm": [],
    "shinegreymon-bm": [],
    "shogungekomon": ["plesiomon","leviamon","vikemon"],
    "shoutmon": ["omega-shoutmon"],
    "silphymon": ["dynasmon","phoenixmon","sakuyamon"],
    "skullgreymon": ["creepymon","shinegreymon","titamon"],
    "skullmeramon": ["gankoomon","beelzemon","boltmon"],
    "slayerdramon": ["examon"],
    "solarmon": ["clockmon","geremon","starmon","meramon"],
    "sorcermon": ["antylamon","piximon","wisemon"],
    "starmon": ["mamemon","metalmamemon","superstarmon"],
    "stingmon": ["infermon","paildramon","okuwamon"],
    "sukamon": ["superstarmon","etemon","vademon"],
    "sunflowmon": ["angewomon","lilamon","lillymon"],
    "superstarmon": ["justimon","gankoomon","platinumnumemon"],
    "susanoomon": [],
    "syakomon": ["ikkakumon","shellnumemon","gekomon","seadramon"],
    "tanemon": ["palmon","lalamon","renamon"],
    "tanemon-mutant": ["renamon-mutant"],
    "tankmon": ["andromon","gigadramon","cannonbeemon","knightmon"],
    "taomon": ["dianamon","kuzuhamon","sakuyamon","phoenixmon"],
    "taomon-mutant": ["sakuyamon-mutant"],
    "tentomon": ["kabuterimon","waspmon","kuwagamon","stingmon","sunflowmon"],
    "terriermon": ["gargomon","ikkakumon","gatomon","rapidmon-gold"],
    "terriermon-mutant": ["gargomon-mutant"],
    "tigervespamon": [],
    "titamon": [],
    "togemon": ["machgaogamon","lillymon","pumpkinmon"],
    "tokomon": ["patamon","falcomon","hawkmon","lucemon"],
    "toyagumon": ["clockmon","greymon","guardromon","sukamon","starmon"],
    "tsumemon": ["agumon-black","keramon","demidevimon"],
    "tsunomon": ["gabumon","gabumon-black","goblimon","veemon","gumdramon","zubamon"],
    "tyrannomon": ["mamemon","megadramon","metalgreymon-blue","metaltyrannomon"],
    "ulforceveedramon": [],
    "vademon": ["ebemon","herculeskabuterimon","hiandromon"],
    "veedramon": ["aeroveedramon","cyberdramon","metaltyrannomon","wargrowlmon"],
    "tentomon-mutant": ["kabuterimon-mutant"],
    "veemon": ["flamedramon","magnamon","veedramon","exveemon"],
    "vegiemon": ["digitamamon","lilamon","megakabuterimon"],
    "venommyotismon": [],
    "vikemon": [],
    "volcanicdramon": [],
    "wanyamon": ["gaomon","kudamon","dorumon"],
    "wargreymon-x": [],
    "wargreymon": ["omegamon","wargreymon-x"],
    "wargrowlmon": ["gallantmon","chaosgallantmon","rusttyranomon"],
    "waspmon": ["cannonbeemon","rapidmon","megakabuterimon","okuwamon"],
    "weregarurumon": ["metalgarurumon","metalgarurumon-black","miragegaogamon"],
    "weregarurumon-black": ["metalgarurumon-black","minervamon","bancholeomon"],
    "whamon": ["plesiomon","marineangemon","metalseadramon"],
    "whamon-mutant": ["plesiomon-mutant"],
    "wingdramon": ["slayerdramon"],
    "wisemon": ["venommyotismon","piedmon","belphemon-sm"],
    "wizardmon": ["skullmeramon","myotismon","wisemon"],
    "woodmon": ["cherrymon","pumpkinmon","taomon"],
    "wormmon": ["waspmon","kabuterimon","kuwagamon","stingmon","icedevimon"],
    "yokomon": ["elecmon","biyomon","wormmon"],
    "zubaeagermon": ["duramon"],
    "zubamon": ["zubaeagermon"],
    "zudomon": ["metalgarurumon","marineangemon","vikemon"]
};

function next(mon) {
    return digi[mon];
}

function prev(mon) {
    var list = [];
    for (key in digi) {
        if (next(key).includes(mon)) {
            list.push(key);
        }
    }
    return list;
}

var input = document.getElementById("in");
var output = document.getElementById("out");

function autocomplete() {
    output.innerHTML = "";
    var mons = Object.keys(digi);
    mons.forEach(function (mon) {
        if (mon.includes(input.value.toLowerCase())) {
            var span = document.createElement("span");
            span.className = "mon";
            span.innerHTML = mon;
            span.addEventListener("click", function (e) {
                output.innerHTML = "previous: " + prev(mon) + "<br>next: " + next(mon);
            });
            output.appendChild(span);
            var br = document.createElement("br");
            output.appendChild(br);
        }
    });
}

input.addEventListener("input", autocomplete);
