var digi = {
	"aeroveedramon": {"evol": "ultimate", "dvol": ["ravemon", "dynasmon", "ulforceveedramon"]}, 
	"agumon": {"evol": "rookie", "dvol": ["geogreymon", "greymon", "meramon", "tyrannomon", "sukamon"]}, 
	"agumon-black": {"evol": "rookie", "dvol": ["growlmon", "cyclonemon", "tankmon", "tyrannomon", "greymon-blue"]}, 
	"alphamon": {"evol": "mega", "dvol": []}, 
	"ancientgreymon": {"evol": "mega", "dvol": []}, 
	"andromon": {"evol": "ultimate", "dvol": ["craniamon", "hiandromon", "tigervespamon"]}, 
	"angemon": {"evol": "champion", "dvol": ["garudamon", "magnaangemon", "shakkoumon", "kimeramon"]}, 
	"angewomon": {"evol": "ultimate", "dvol": ["magnadramon", "ophanimon", "mastemon"]}, 
	"ankylomon": {"evol": "champion", "dvol": ["magnaangemon", "meteormon", "shakkoumon", "skullgreymon"]}, 
	"antylamon": {"evol": "ultimate", "dvol": ["cherubimon-good", "dianamon", "diaboromon", "chaosgallantmon"]}, 
	"aquilamon": {"evol": "champion", "dvol": ["aeroveedramon", "garudamon", "silphymon", "crowmon"]}, 
	"armadillomon": {"evol": "rookie", "dvol": ["ankylomon", "cyclonemon", "goldnumemon", "tankmon", "geremon"]}, 
	"arresterdramon": {"evol": "mega", "dvol": []}, 
	"bakemon": {"evol": "champion", "dvol": ["bluemeramon", "pumpkinmon", "myotismon", "ladydevimon"]}, 
	"bancholeomon": {"evol": "mega", "dvol": []}, 
	"barbamon": {"evol": "mega", "dvol": []}, 
	"beelzemon": {"evol": "mega", "dvol": []}, 
	"belphemon-rm": {"evol": "mega", "dvol": ["belphemon-sm"]}, 
	"belphemon-sm": {"evol": "mega", "dvol": ["belphemon-rm"]}, 
	"betamon": {"evol": "rookie", "dvol": ["gekomon", "numemon", "seadramon", "shellnumemon", "vegiemon"]}, 
	"birdramon": {"evol": "champion", "dvol": ["aeroveedramon", "garudamon", "chirinmon", "crowmon"]}, 
	"biyomon": {"evol": "rookie", "dvol": ["kabuterimon", "aquilamon", "birdramon", "kyubimon"]}, 
	"blackgatomon": {"evol": "champion", "dvol": ["cyberdramon", "knightmon", "ladydevimon", "weregarurumon-black"]}, 
	"blackkingnumemon": {"evol": "ultimate", "dvol": ["platinumnumemon", "metaletemon", "princemamemon"]}, 
	"blackwargreymon": {"evol": "mega", "dvol": ["omegamon-zwart", "blackwargreymon-x"]}, 
	"blackwargreymon-x": {"evol": "mega", "dvol": []}, 
	"bluemeramon": {"evol": "ultimate", "dvol": ["barbamon", "boltmon", "creepymon"]}, 
	"boltmon": {"evol": "mega", "dvol": []}, 
	"botamon": {"evol": "in-training-i", "dvol": ["koromon", "wanyamon"]}, 
	"breakdramon": {"evol": "mega", "dvol": ["examon"]}, 
	"bukamon": {"evol": "in-training-ii", "dvol": ["otamamon", "gomamon", "syakomon", "betamon"]}, 
	"cannonbeemon": {"evol": "ultimate", "dvol": ["megagargomon", "groundlocomon", "tigervespamon"]}, 
	"chaosdramon": {"evol": "mega", "dvol": []}, 
	"chaosgallantmon": {"evol": "mega", "dvol": []}, 
	"cherrymon": {"evol": "ultimate", "dvol": ["grankuwagamon", "kuzuhamon", "puppetmon"]}, 
	"cherubimon-good": {"evol": "mega", "dvol": []}, 
	"chirinmon": {"evol": "ultimate", "dvol": ["ophanimon", "seraphimon", "kentaurosmon"]}, 
	"chrysalimon": {"evol": "champion", "dvol": ["cyberdramon", "infermon", "taomon"]}, 
	"clockmon": {"evol": "champion", "dvol": ["andromon", "knightmon", "datamon", "wisemon"]}, 
	"coredramon-blue": {"evol": "champion", "dvol": ["wingdramon"]}, 
	"coredramon-green": {"evol": "champion", "dvol": ["groundramon"]}, 
	"craniamon": {"evol": "mega", "dvol": []}, 
	"creepymon": {"evol": "mega", "dvol": []}, 
	"crowmon": {"evol": "ultimate", "dvol": ["minervamon", "ravemon", "kuzuhamon"]}, 
	"cyberdramon": {"evol": "ultimate", "dvol": ["justimon", "titamon", "alphamon"]}, 
	"cyclonemon": {"evol": "champion", "dvol": ["megadramon", "dorugreymon", "datamon"]}, 
	"datamon": {"evol": "ultimate", "dvol": ["machinedramon", "metalgarurumon-black", "groundlocomon"]}, 
	"demidevimon": {"evol": "rookie", "dvol": ["bakemon", "devimon", "kyubimon", "chrysalimon", "icedevimon"]}, 
	"devimon": {"evol": "champion", "dvol": ["bluemeramon", "infermon", "metalgreymon-blue", "myotismon", "kimeramon"]}, 
	"diaboromon": {"evol": "mega", "dvol": []}, 
	"dianamon": {"evol": "mega", "dvol": []}, 
	"digitamamon": {"evol": "ultimate", "dvol": ["minervamon", "belphemon-sm", "titamon"]}, 
	"dorugamon": {"evol": "champion", "dvol": ["rizegreymon", "dorugreymon", "chirinmon"]}, 
	"dorugreymon": {"evol": "ultimate", "dvol": ["alphamon", "kentaurosmon"]}, 
	"dorumon": {"evol": "rookie", "dvol": ["cyclonemon", "dorugamon", "guardromon", "waspmon"]}, 
	"dracomon": {"evol": "rookie", "dvol": ["coredramon-blue", "coredramon-green"]}, 
	"duramon": {"evol": "ultimate", "dvol": ["durandamon"]}, 
	"durandamon": {"evol": "mega", "dvol": []}, 
	"dynasmon": {"evol": "mega", "dvol": []}, 
	"ebemon": {"evol": "mega", "dvol": []}, 
	"elecmon": {"evol": "rookie", "dvol": ["garurumon", "leomon", "nanimon", "sukamon", "garurumon-black", "geremon"]}, 
	"etemon": {"evol": "ultimate", "dvol": ["metaletemon", "piedmon", "platinumnumemon", "kingetemon"]}, 
	"examon": {"evol": "mega", "dvol": []}, 
	"exveemon": {"evol": "champion", "dvol": ["magnaangemon", "paildramon", "rizegreymon"]}, 
	"falcomon": {"evol": "rookie", "dvol": ["stingmon", "exveemon", "aquilamon", "peckmon"]}, 
	"flamedramon": {"evol": "champion", "dvol": []}, 
	"frigimon": {"evol": "champion", "dvol": ["zudomon", "angewomon", "monzaemon"]}, 
	"gabumon": {"evol": "rookie", "dvol": ["dorugamon", "garurumon", "numemon", "veedramon", "frigimon"]}, 
	"gabumon-black": {"evol": "rookie", "dvol": ["garurumon-black", "vegiemon", "reppamon", "frigimon"]}, 
	"gaiomon": {"evol": "mega", "dvol": ["susanoomon"]}, 
	"gallantmon": {"evol": "mega", "dvol": ["gallantmon-cm", "gallantmon-x"]}, 
	"gallantmon-cm": {"evol": "mega", "dvol": []}, 
	"gallantmon-x": {"evol": "mega", "dvol": []}, 
	"gankoomon": {"evol": "mega", "dvol": []}, 
	"gaogamon": {"evol": "champion", "dvol": ["grapleomon", "machgaogamon", "weregarurumon"]}, 
	"gaomon": {"evol": "rookie", "dvol": ["gargomon", "gaogamon", "leomon", "togemon", "ogremon"]}, 
	"gargomon": {"evol": "champion", "dvol": ["wargrowlmon", "antylamon", "rapidmon"]}, 
	"garudamon": {"evol": "ultimate", "dvol": ["phoenixmon", "justimon", "ravemon"]}, 
	"garurumon": {"evol": "champion", "dvol": ["dorugreymon", "iceleomon", "weregarurumon", "zudomon", "kimeramon"]}, 
	"garurumon-black": {"evol": "champion", "dvol": ["weregarurumon-black", "bluemeramon", "machgaogamon"]}, 
	"gatomon": {"evol": "champion", "dvol": ["angewomon", "lillymon", "silphymon"]}, 
	"gazimon": {"evol": "rookie", "dvol": ["dorugamon", "gaogamon", "leomon", "chrysalimon", "nanimon", "garurumon-black"]}, 
	"gekomon": {"evol": "champion", "dvol": ["megaseadramon", "shogungekomon", "whamon"]}, 
	"geogreymon": {"evol": "champion", "dvol": ["gigadramon", "rizegreymon", "skullgreymon"]}, 
	"geremon": {"evol": "champion", "dvol": ["etemon", "superstarmon", "metalmamemon"]}, 
	"gigadramon": {"evol": "ultimate", "dvol": ["metalseadramon", "machinedramon", "groundlocomon"]}, 
	"goblimon": {"evol": "rookie", "dvol": ["gaogamon", "growlmon", "nanimon", "ogremon", "greymon-blue"]}, 
	"goldnumemon": {"evol": "champion", "dvol": ["vademon", "platinumnumemon", "blackkingnumemon"]}, 
	"gomamon": {"evol": "rookie", "dvol": ["ankylomon", "ikkakumon", "sorcermon", "frigimon"]}, 
	"gotsumon": {"evol": "rookie", "dvol": ["ankylomon", "clockmon", "starmon", "tankmon"]}, 
	"grankuwagamon": {"evol": "mega", "dvol": []}, 
	"grapleomon": {"evol": "ultimate", "dvol": ["bancholeomon", "leopardmon", "saberleomon"]}, 
	"greymon": {"evol": "champion", "dvol": ["metalgreymon", "metalgreymon-blue", "megadramon", "skullgreymon", "kimeramon"]}, 
	"greymon-blue": {"evol": "champion", "dvol": ["metalgreymon-blue", "knightmon", "dorugreymon"]}, 
	"groundlocomon": {"evol": "mega", "dvol": []}, 
	"groundramon": {"evol": "ultimate", "dvol": ["breakdramon"]}, 
	"growlmon": {"evol": "champion", "dvol": ["gigadramon", "wargrowlmon", "metalgreymon", "metaltyrannomon"]}, 
	"guardromon": {"evol": "champion", "dvol": ["andromon", "grapleomon", "metalmamemon", "datamon"]}, 
	"guilmon": {"evol": "rookie", "dvol": ["geogreymon", "growlmon", "meramon", "tyrannomon", "greymon-blue"]}, 
	"gumdramon": {"evol": "rookie", "dvol": ["arresterdramon"]}, 
	"hackmon": {"evol": "rookie", "dvol": ["jesmon", "greymon", "geogreymon", "platinumsukamon"]}, 
	"hagurumon": {"evol": "rookie", "dvol": ["clockmon", "goldnumemon", "guardromon", "starmon", "platinumsukamon"]}, 
	"hawkmon": {"evol": "rookie", "dvol": ["meramon", "aquilamon", "birdramon", "peckmon"]}, 
	"herculeskabuterimon": {"evol": "mega", "dvol": []}, 
	"hiandromon": {"evol": "mega", "dvol": []}, 
	"icedevimon": {"evol": "champion", "dvol": ["myotismon", "cherrymon", "ladydevimon"]}, 
	"iceleomon": {"evol": "ultimate", "dvol": ["bancholeomon", "saberleomon", "miragegaogamon"]}, 
	"ikkakumon": {"evol": "champion", "dvol": ["machgaogamon", "whamon", "zudomon"]}, 
	"imperialdramon-dm": {"evol": "mega", "dvol": ["imperialdramon-fm"]}, 
	"imperialdramon-fm": {"evol": "mega", "dvol": ["imperialdramon-pm"]}, 
	"imperialdramon-pm": {"evol": "mega", "dvol": []}, 
	"impmon": {"evol": "rookie", "dvol": ["bakemon", "ogremon", "sorcermon", "blackgatomon", "wizardmon", "icedevimon"]}, 
	"infermon": {"evol": "ultimate", "dvol": ["beelzemon", "diaboromon", "venommyotismon"]}, 
	"jesmon": {"evol": "mega", "dvol": []}, 
	"justimon": {"evol": "mega", "dvol": []}, 
	"kabuterimon": {"evol": "champion", "dvol": ["megakabuterimon", "cherrymon", "lilamon", "kimeramon"]}, 
	"kentaurosmon": {"evol": "mega", "dvol": []}, 
	"keramon": {"evol": "rookie", "dvol": ["bakemon", "wizardmon", "chrysalimon", "platinumsukamon"]}, 
	"kimeramon": {"evol": "ultimate", "dvol": ["millenniummon"]}, 
	"kingetemon": {"evol": "mega", "dvol": []}, 
	"knightmon": {"evol": "ultimate", "dvol": ["craniamon", "leopardmon", "lordknightmon"]}, 
	"koromon": {"evol": "in-training-ii", "dvol": ["agumon", "guilmon", "toyagumon", "hackmon", "dracomon", "shoutmon"]}, 
	"kudamon": {"evol": "rookie", "dvol": ["angemon", "goldnumemon", "peckmon", "reppamon"]}, 
	"kuramon": {"evol": "in-training-i", "dvol": ["tsumemon", "pagumon"]}, 
	"kuwagamon": {"evol": "champion", "dvol": ["cherrymon", "okuwamon", "cannonbeemon", "kimeramon"]}, 
	"kuzuhamon": {"evol": "mega", "dvol": []}, 
	"kyubimon": {"evol": "champion", "dvol": ["ladydevimon", "monzaemon", "taomon"]}, 
	"ladydevimon": {"evol": "ultimate", "dvol": ["lilithmon", "lotosmon", "mastemon"]}, 
	"lalamon": {"evol": "rookie", "dvol": ["sunflowmon", "togemon", "vegiemon", "woodmon"]}, 
	"leomon": {"evol": "champion", "dvol": ["grapleomon", "metalgreymon", "meteormon", "iceleomon"]}, 
	"leopardmon": {"evol": "mega", "dvol": ["leopardmon-lm"]}, 
	"leopardmon-lm": {"evol": "mega", "dvol": []}, 
	"leviamon": {"evol": "mega", "dvol": []}, 
	"lilamon": {"evol": "ultimate", "dvol": ["lilithmon", "lotosmon", "rosemon"]}, 
	"lilithmon": {"evol": "mega", "dvol": []}, 
	"lillymon": {"evol": "ultimate", "dvol": ["magnadramon", "lotosmon", "rosemon"]}, 
	"lopmon": {"evol": "rookie", "dvol": ["gargomon", "devimon", "blackgatomon", "wizardmon"]}, 
	"lordknightmon": {"evol": "mega", "dvol": []}, 
	"lotosmon": {"evol": "mega", "dvol": []}, 
	"lucemon": {"evol": "rookie", "dvol": ["angemon", "devimon", "lucemon-fm"]}, 
	"lucemon-fm": {"evol": "ultimate", "dvol": ["lucemon-sm"]}, 
	"lucemon-sm": {"evol": "mega", "dvol": []}, 
	"machgaogamon": {"evol": "ultimate", "dvol": ["bancholeomon", "miragegaogamon", "megagargomon"]}, 
	"machinedramon": {"evol": "mega", "dvol": ["millenniummon", "chaosdramon"]}, 
	"magnaangemon": {"evol": "ultimate", "dvol": ["shinegreymon", "lordknightmon", "seraphimon"]}, 
	"magnadramon": {"evol": "mega", "dvol": []}, 
	"magnamon": {"evol": "mega", "dvol": ["magnamon-x"]}, 
	"magnamon-x": {"evol": "mega", "dvol": []}, 
	"mamemon": {"evol": "ultimate", "dvol": ["puppetmon", "princemamemon", "wargreymon"]}, 
	"marineangemon": {"evol": "mega", "dvol": []}, 
	"mastemon": {"evol": "mega", "dvol": []}, 
	"megadramon": {"evol": "ultimate", "dvol": ["blackwargreymon", "machinedramon", "ulforceveedramon"]}, 
	"megagargomon": {"evol": "mega", "dvol": []}, 
	"megakabuterimon": {"evol": "ultimate", "dvol": ["grankuwagamon", "herculeskabuterimon", "magnadramon"]}, 
	"megaseadramon": {"evol": "ultimate", "dvol": ["leviamon", "metalseadramon", "plesiomon"]}, 
	"meicoomon": {"evol": "champion", "dvol": ["meicrackmon-vm"]}, 
	"meicrackmon-vm": {"evol": "ultimate", "dvol": ["raguelmon"]}, 
	"meramon": {"evol": "champion", "dvol": ["bluemeramon", "skullmeramon", "mamemon", "iceleomon"]}, 
	"metaletemon": {"evol": "mega", "dvol": []}, 
	"metalgarurumon": {"evol": "mega", "dvol": ["omegamon", "metalgarurumon-x"]}, 
	"metalgarurumon-black": {"evol": "mega", "dvol": ["omegamon-zwart"]}, 
	"metalgarurumon-x": {"evol": "mega", "dvol": []}, 
	"metalgreymon": {"evol": "ultimate", "dvol": ["rusttyranomon", "gaiomon", "wargreymon", "ancientgreymon"]}, 
	"metalgreymon-blue": {"evol": "ultimate", "dvol": ["wargreymon", "gaiomon", "blackwargreymon"]}, 
	"metalmamemon": {"evol": "ultimate", "dvol": ["ebemon", "hiandromon", "princemamemon"]}, 
	"metalseadramon": {"evol": "mega", "dvol": []}, 
	"metaltyrannomon": {"evol": "ultimate", "dvol": ["blackwargreymon", "gallantmon", "rusttyranomon"]}, 
	"meteormon": {"evol": "ultimate", "dvol": ["ebemon", "metaletemon", "dianamon", "metalgarurumon"]}, 
	"millenniummon": {"evol": "mega", "dvol": []}, 
	"minervamon": {"evol": "mega", "dvol": []}, 
	"miragegaogamon": {"evol": "mega", "dvol": ["omegamon-zwart-d", "miragegaogamon-bm"]}, 
	"miragegaogamon-bm": {"evol": "mega", "dvol": []}, 
	"monzaemon": {"evol": "ultimate", "dvol": ["minervamon", "sakuyamon", "saberleomon"]}, 
	"motimon": {"evol": "in-training-ii", "dvol": ["gotsumon", "solarmon", "tentomon", "hagurumon"]}, 
	"myotismon": {"evol": "ultimate", "dvol": ["barbamon", "piedmon", "venommyotismon"]}, 
	"nanimon": {"evol": "champion", "dvol": ["digitamamon", "superstarmon", "meteormon"]}, 
	"numemon": {"evol": "champion", "dvol": ["blackkingnumemon", "etemon", "monzaemon"]}, 
	"nyaromon": {"evol": "in-training-ii", "dvol": ["armadillomon", "terriermon", "salamon"]}, 
	"ogremon": {"evol": "champion", "dvol": ["skullmeramon", "digitamamon", "weregarurumon"]}, 
	"okuwamon": {"evol": "ultimate", "dvol": ["diaboromon", "grankuwagamon", "herculeskabuterimon"]}, 
	"omega-shoutmon": {"evol": "mega", "dvol": []}, 
	"omegamon": {"evol": "mega", "dvol": ["omegamon-x"]}, 
	"omegamon-alter-b": {"evol": "mega", "dvol": []}, 
	"omegamon-x": {"evol": "mega", "dvol": []}, 
	"omegamon-zwart": {"evol": "mega", "dvol": []}, 
	"omegamon-zwart-d": {"evol": "mega", "dvol": ["omegamon-alter-b"]}, 
	"ophanimon": {"evol": "mega", "dvol": []}, 
	"otamamon": {"evol": "rookie", "dvol": ["gekomon", "numemon", "seadramon", "shellnumemon"]}, 
	"pabumon": {"evol": "in-training-i", "dvol": ["tanemon", "yokomon", "motimon"]}, 
	"pagumon": {"evol": "in-training-ii", "dvol": ["impmon", "gazimon", "lopmon"]}, 
	"paildramon": {"evol": "ultimate", "dvol": ["imperialdramon-dm"]}, 
	"palmon": {"evol": "rookie", "dvol": ["kuwagamon", "togemon", "vegiemon", "sunflowmon", "woodmon"]}, 
	"patamon": {"evol": "rookie", "dvol": ["angemon", "birdramon", "reppamon", "gatomon", "exveemon"]}, 
	"peckmon": {"evol": "champion", "dvol": ["antylamon", "piximon", "crowmon"]}, 
	"phoenixmon": {"evol": "mega", "dvol": []}, 
	"piedmon": {"evol": "mega", "dvol": []}, 
	"piximon": {"evol": "ultimate", "dvol": ["cherubimon-good", "marineangemon", "ophanimon"]}, 
	"platinumnumemon": {"evol": "mega", "dvol": []}, 
	"platinumsukamon": {"evol": "champion", "dvol": ["etemon", "metalmamemon", "vademon"]}, 
	"plesiomon": {"evol": "mega", "dvol": []}, 
	"poyomon": {"evol": "in-training-i", "dvol": ["tokomon", "bukamon"]}, 
	"princemamemon": {"evol": "mega", "dvol": []}, 
	"pumpkinmon": {"evol": "ultimate", "dvol": ["boltmon", "puppetmon", "rosemon"]}, 
	"punimon": {"evol": "in-training-i", "dvol": ["tsunomon", "nyaromon"]}, 
	"puppetmon": {"evol": "mega", "dvol": []}, 
	"raguelmon": {"evol": "mega", "dvol": []}, 
	"rapidmon": {"evol": "ultimate", "dvol": ["megagargomon", "tigervespamon", "metalgarurumon-black"]}, 
	"rapidmon-gold": {"evol": "champion", "dvol": []}, 
	"ravemon": {"evol": "mega", "dvol": ["ravemon-bm"]}, 
	"ravemon-bm": {"evol": "mega", "dvol": []}, 
	"renamon": {"evol": "rookie", "dvol": ["blackgatomon", "garurumon", "kyubimon", "woodmon"]}, 
	"reppamon": {"evol": "champion", "dvol": ["rapidmon", "piximon", "chirinmon"]}, 
	"rizegreymon": {"evol": "ultimate", "dvol": ["gaiomon", "shinegreymon"]}, 
	"rosemon": {"evol": "mega", "dvol": ["rosemon-bm"]}, 
	"rosemon-bm": {"evol": "mega", "dvol": []}, 
	"rusttyranomon": {"evol": "mega", "dvol": []}, 
	"saberleomon": {"evol": "mega", "dvol": []}, 
	"sakuyamon": {"evol": "mega", "dvol": []}, 
	"salamon": {"evol": "rookie", "dvol": ["frigimon", "reppamon", "gatomon", "veedramon", "sorcermon"]}, 
	"seadramon": {"evol": "champion", "dvol": ["shogungekomon", "megaseadramon", "whamon"]}, 
	"seraphimon": {"evol": "mega", "dvol": []}, 
	"shakkoumon": {"evol": "ultimate", "dvol": ["cherubimon-good", "vikemon", "seraphimon"]}, 
	"shellnumemon": {"evol": "champion", "dvol": ["blackkingnumemon", "megaseadramon", "shogungekomon"]}, 
	"shinegreymon": {"evol": "mega", "dvol": ["omegamon-zwart-d", "shinegreymon-bm", "shinegreymon-rm"]}, 
	"shinegreymon-bm": {"evol": "mega", "dvol": []}, 
	"shinegreymon-rm": {"evol": "mega", "dvol": []}, 
	"shogungekomon": {"evol": "ultimate", "dvol": ["plesiomon", "leviamon", "vikemon"]}, 
	"shoutmon": {"evol": "rookie", "dvol": ["omega-shoutmon"]}, 
	"silphymon": {"evol": "ultimate", "dvol": ["dynasmon", "phoenixmon", "sakuyamon"]}, 
	"skullgreymon": {"evol": "ultimate", "dvol": ["creepymon", "shinegreymon", "titamon"]}, 
	"skullmeramon": {"evol": "ultimate", "dvol": ["gankoomon", "beelzemon", "boltmon"]}, 
	"slayerdramon": {"evol": "mega", "dvol": ["examon"]}, 
	"solarmon": {"evol": "rookie", "dvol": ["clockmon", "geremon", "starmon", "meramon"]}, 
	"sorcermon": {"evol": "champion", "dvol": ["antylamon", "piximon", "wisemon"]}, 
	"starmon": {"evol": "champion", "dvol": ["mamemon", "metalmamemon", "superstarmon"]}, 
	"stingmon": {"evol": "champion", "dvol": ["infermon", "paildramon", "okuwamon"]}, 
	"sukamon": {"evol": "champion", "dvol": ["superstarmon", "etemon", "vademon"]}, 
	"sunflowmon": {"evol": "champion", "dvol": ["angewomon", "lilamon", "lillymon"]}, 
	"superstarmon": {"evol": "ultimate", "dvol": ["justimon", "gankoomon", "platinumnumemon"]}, 
	"susanoomon": {"evol": "mega", "dvol": []}, 
	"syakomon": {"evol": "rookie", "dvol": ["ikkakumon", "shellnumemon", "gekomon", "seadramon"]}, 
	"tanemon": {"evol": "in-training-ii", "dvol": ["palmon", "lalamon", "renamon"]}, 
	"tankmon": {"evol": "champion", "dvol": ["andromon", "gigadramon", "cannonbeemon", "knightmon"]}, 
	"taomon": {"evol": "ultimate", "dvol": ["dianamon", "kuzuhamon", "sakuyamon", "phoenixmon"]}, 
	"tentomon": {"evol": "rookie", "dvol": ["kabuterimon", "waspmon", "kuwagamon", "stingmon", "sunflowmon"]}, 
	"terriermon": {"evol": "rookie", "dvol": ["gargomon", "ikkakumon", "gatomon", "rapidmon-gold"]}, 
	"tigervespamon": {"evol": "mega", "dvol": []}, 
	"titamon": {"evol": "mega", "dvol": []}, 
	"togemon": {"evol": "champion", "dvol": ["machgaogamon", "lillymon", "pumpkinmon"]}, 
	"tokomon": {"evol": "in-training-ii", "dvol": ["patamon", "falcomon", "hawkmon", "lucemon"]}, 
	"toyagumon": {"evol": "rookie", "dvol": ["clockmon", "greymon", "guardromon", "sukamon", "starmon"]}, 
	"tsumemon": {"evol": "in-training-ii", "dvol": ["agumon-black", "keramon", "demidevimon"]}, 
	"tsunomon": {"evol": "in-training-ii", "dvol": ["gabumon", "gabumon-black", "goblimon", "veemon", "gumdramon", "zubamon"]}, 
	"tyrannomon": {"evol": "champion", "dvol": ["mamemon", "megadramon", "metalgreymon-blue", "metaltyrannomon"]}, 
	"ulforceveedramon": {"evol": "mega", "dvol": []}, 
	"vademon": {"evol": "ultimate", "dvol": ["ebemon", "herculeskabuterimon", "hiandromon"]}, 
	"veedramon": {"evol": "champion", "dvol": ["aeroveedramon", "cyberdramon", "metaltyrannomon", "wargrowlmon"]}, 
	"veemon": {"evol": "rookie", "dvol": ["flamedramon", "magnamon", "veedramon", "exveemon"]}, 
	"vegiemon": {"evol": "champion", "dvol": ["digitamamon", "lilamon", "megakabuterimon"]}, 
	"venommyotismon": {"evol": "mega", "dvol": []}, 
	"vikemon": {"evol": "mega", "dvol": []}, 
	"volcanicdramon": {"evol": "mega", "dvol": []}, 
	"wanyamon": {"evol": "in-training-ii", "dvol": ["gaomon", "kudamon", "dorumon"]}, 
	"wargreymon": {"evol": "mega", "dvol": ["omegamon", "wargreymon-x"]}, 
	"wargreymon-x": {"evol": "mega", "dvol": []}, 
	"wargrowlmon": {"evol": "ultimate", "dvol": ["gallantmon", "chaosgallantmon", "rusttyranomon"]}, 
	"waspmon": {"evol": "champion", "dvol": ["cannonbeemon", "rapidmon", "megakabuterimon", "okuwamon"]}, 
	"weregarurumon": {"evol": "ultimate", "dvol": ["metalgarurumon", "metalgarurumon-black", "miragegaogamon"]}, 
	"weregarurumon-black": {"evol": "ultimate", "dvol": ["metalgarurumon-black", "minervamon", "bancholeomon"]}, 
	"whamon": {"evol": "ultimate", "dvol": ["plesiomon", "marineangemon", "metalseadramon"]}, 
	"wingdramon": {"evol": "ultimate", "dvol": ["slayerdramon"]}, 
	"wisemon": {"evol": "ultimate", "dvol": ["venommyotismon", "piedmon", "belphemon-sm"]}, 
	"wizardmon": {"evol": "champion", "dvol": ["skullmeramon", "myotismon", "wisemon"]}, 
	"woodmon": {"evol": "champion", "dvol": ["cherrymon", "pumpkinmon", "taomon"]}, 
	"wormmon": {"evol": "rookie", "dvol": ["waspmon", "kabuterimon", "kuwagamon", "stingmon", "icedevimon"]}, 
	"yokomon": {"evol": "in-training-ii", "dvol": ["elecmon", "biyomon", "wormmon"]}, 
	"zubaeagermon": {"evol": "champion", "dvol": ["duramon"]}, 
	"zubamon": {"evol": "rookie", "dvol": ["zubaeagermon"]}, 
	"zudomon": {"evol": "ultimate", "dvol": ["metalgarurumon", "marineangemon", "vikemon"]}
};
